package com.matianju.fm;

import android.content.*;
import android.database.Cursor;
import android.database.sqlite.*;
import android.net.Uri;
import android.provider.DocumentsContract;
import java.util.*;

public final class LibraryDb extends SQLiteOpenHelper {
    static final String DB_NAME = "matianju.db";
    private static LibraryDb instance;
    public static synchronized LibraryDb get(Context c) {
        if (instance == null) instance = new LibraryDb(c.getApplicationContext());
        return instance;
    }
    private LibraryDb(Context c) { super(c, DB_NAME, null, 3); }

    @Override public void onCreate(SQLiteDatabase db) {
        db.execSQL("CREATE TABLE roots(uri TEXT PRIMARY KEY,name TEXT NOT NULL,added INTEGER NOT NULL)");
        db.execSQL("CREATE TABLE folders(id TEXT PRIMARY KEY,root_uri TEXT NOT NULL,parent_id TEXT,name TEXT NOT NULL,path TEXT NOT NULL,last_scan INTEGER DEFAULT 0,last_played INTEGER DEFAULT 0)");
        db.execSQL("CREATE TABLE tracks(uri TEXT PRIMARY KEY,folder_id TEXT NOT NULL,name TEXT NOT NULL,title TEXT,artist TEXT,duration INTEGER DEFAULT 0,size INTEGER DEFAULT 0,modified INTEGER DEFAULT 0,position INTEGER DEFAULT 0,completed INTEGER DEFAULT 0,last_played INTEGER DEFAULT 0,favorite INTEGER DEFAULT 0)");
        db.execSQL("CREATE INDEX track_folder ON tracks(folder_id)");
        db.execSQL("CREATE TABLE bookmarks(id INTEGER PRIMARY KEY AUTOINCREMENT,track_uri TEXT NOT NULL,position INTEGER NOT NULL,note TEXT,created INTEGER NOT NULL)");
        db.execSQL("CREATE TABLE settings(key TEXT PRIMARY KEY,value TEXT)");
        db.execSQL("CREATE TABLE excluded_folders(id TEXT PRIMARY KEY,root_uri TEXT NOT NULL,name TEXT NOT NULL,path TEXT NOT NULL,excluded INTEGER NOT NULL)");
        db.execSQL("CREATE TABLE scan_roots(id TEXT PRIMARY KEY,permission_uri TEXT NOT NULL,document_id TEXT NOT NULL,name TEXT NOT NULL,path TEXT NOT NULL,added INTEGER NOT NULL)");
    }
    @Override public void onUpgrade(SQLiteDatabase db, int oldV, int newV) {if(oldV<2)db.execSQL("CREATE TABLE excluded_folders(id TEXT PRIMARY KEY,root_uri TEXT NOT NULL,name TEXT NOT NULL,path TEXT NOT NULL,excluded INTEGER NOT NULL)");if(oldV<3)db.execSQL("CREATE TABLE scan_roots(id TEXT PRIMARY KEY,permission_uri TEXT NOT NULL,document_id TEXT NOT NULL,name TEXT NOT NULL,path TEXT NOT NULL,added INTEGER NOT NULL)");}

    public static final class Folder {
        public String id, rootUri, parentId, name, path;
        public long totalDuration, lastPlayed;
        public int count, completed;
    }
    public static final class Track {
        public String uri, folderId, name, title, artist, folderPath;
        public long duration, size, modified, position, lastPlayed;
        public boolean completed, favorite;
        public String displayTitle() { return title == null || title.trim().isEmpty() ? name : title; }
    }
    public static final class ScanRoot {
        public String id, permissionUri, documentId, name, path;
    }

    public void upsertRoot(String uri, String name) {
        ContentValues v = new ContentValues(); v.put("uri",uri); v.put("name",name); v.put("added",System.currentTimeMillis());
        getWritableDatabase().insertWithOnConflict("roots",null,v,SQLiteDatabase.CONFLICT_REPLACE);
    }
    public List<String[]> roots() {
        ArrayList<String[]> out=new ArrayList<>();
        try(Cursor c=getReadableDatabase().rawQuery("SELECT uri,name FROM roots ORDER BY added",null)){while(c.moveToNext())out.add(new String[]{c.getString(0),c.getString(1)});} return out;
    }
    public void upsertScanRoot(String permissionUri,String documentId,String name,String path){SQLiteDatabase db=getWritableDatabase();ArrayList<String>redundant=new ArrayList<>();try(Cursor c=db.rawQuery("SELECT id,document_id FROM scan_roots WHERE permission_uri=?",new String[]{permissionUri})){while(c.moveToNext()){String existingId=c.getString(0),existingDocumentId=c.getString(1);if(!existingDocumentId.equals(documentId)&&FolderIdentity.isSameOrDescendant(documentId,existingDocumentId))redundant.add(existingId);}}for(String id:redundant)db.delete("scan_roots","id=?",new String[]{id});ContentValues v=new ContentValues();v.put("id",permissionUri+"#"+documentId);v.put("permission_uri",permissionUri);v.put("document_id",documentId);v.put("name",name);v.put("path",path);v.put("added",System.currentTimeMillis());db.insertWithOnConflict("scan_roots",null,v,SQLiteDatabase.CONFLICT_REPLACE);}
    public List<ScanRoot> scanRoots(){migrateLegacyScanRoots();ArrayList<ScanRoot>out=new ArrayList<>();try(Cursor c=getReadableDatabase().rawQuery("SELECT id,permission_uri,document_id,name,path FROM scan_roots ORDER BY added",null)){while(c.moveToNext()){ScanRoot r=new ScanRoot();r.id=c.getString(0);r.permissionUri=c.getString(1);r.documentId=c.getString(2);r.name=c.getString(3);r.path=c.getString(4);out.add(r);}}return out;}
    public ScanRoot coveringScanRoot(String permissionUri,String documentId){ScanRoot best=null;for(ScanRoot root:scanRoots())if(root.permissionUri.equals(permissionUri)&&FolderIdentity.isSameOrDescendant(root.documentId,documentId)&&(best==null||root.documentId.length()>best.documentId.length()))best=root;return best;}
    private void migrateLegacyScanRoots(){if("1".equals(setting("scan_roots_migrated","0")))return;SQLiteDatabase db=getWritableDatabase();for(String[]root:roots()){if(root[0].startsWith("internal://"))continue;boolean alreadyMigrated;try(Cursor c=db.rawQuery("SELECT 1 FROM scan_roots WHERE permission_uri=? LIMIT 1",new String[]{root[0]})){alreadyMigrated=c.moveToFirst();}if(alreadyMigrated)continue;try{String documentId=DocumentsContract.getTreeDocumentId(Uri.parse(root[0]));upsertScanRoot(root[0],documentId,root[1],root[1]);}catch(Exception ignored){}}setSetting("scan_roots_migrated","1");}
    public boolean isScanRoot(String id){migrateLegacyScanRoots();try(Cursor c=getReadableDatabase().rawQuery("SELECT 1 FROM scan_roots WHERE id=?",new String[]{id})){return c.moveToFirst();}}
    /** Removes one selected scan root. Returns true when its persisted permission is no longer used. */
    public boolean removeScanRoot(String id){migrateLegacyScanRoots();SQLiteDatabase db=getWritableDatabase();String permissionUri=null;try(Cursor c=db.rawQuery("SELECT permission_uri FROM scan_roots WHERE id=?",new String[]{id})){if(c.moveToFirst())permissionUri=c.getString(0);}if(permissionUri==null)return false;db.beginTransaction();try{Object[]a={id};db.execSQL("WITH RECURSIVE subtree(id) AS (SELECT ? UNION ALL SELECT x.id FROM folders x JOIN subtree s ON x.parent_id=s.id) DELETE FROM bookmarks WHERE track_uri IN (SELECT uri FROM tracks WHERE folder_id IN (SELECT id FROM subtree))",a);db.execSQL("WITH RECURSIVE subtree(id) AS (SELECT ? UNION ALL SELECT x.id FROM folders x JOIN subtree s ON x.parent_id=s.id) DELETE FROM tracks WHERE folder_id IN (SELECT id FROM subtree)",a);db.execSQL("WITH RECURSIVE subtree(id) AS (SELECT ? UNION ALL SELECT x.id FROM folders x JOIN subtree s ON x.parent_id=s.id) DELETE FROM folders WHERE id IN (SELECT id FROM subtree)",a);db.delete("scan_roots","id=?",new String[]{id});db.setTransactionSuccessful();}finally{db.endTransaction();}boolean unused;try(Cursor c=db.rawQuery("SELECT 1 FROM scan_roots WHERE permission_uri=? LIMIT 1",new String[]{permissionUri})){unused=!c.moveToFirst();}if(unused){db.delete("excluded_folders","root_uri=?",new String[]{permissionUri});db.delete("roots","uri=?",new String[]{permissionUri});}return unused;}
    public void removeRoot(String uri) {
        SQLiteDatabase db=getWritableDatabase(); db.beginTransaction(); try {
            db.delete("bookmarks","track_uri IN (SELECT uri FROM tracks WHERE folder_id IN (SELECT id FROM folders WHERE root_uri=?))",new String[]{uri});
            db.delete("tracks","folder_id IN (SELECT id FROM folders WHERE root_uri=?)",new String[]{uri});
            db.delete("folders","root_uri=?",new String[]{uri});db.delete("excluded_folders","root_uri=?",new String[]{uri});db.delete("scan_roots","permission_uri=?",new String[]{uri});db.delete("roots","uri=?",new String[]{uri}); db.setTransactionSuccessful();
        } finally {db.endTransaction();}
    }
    public void excludeFolder(Folder f){SQLiteDatabase db=getWritableDatabase();db.beginTransaction();try{ContentValues v=new ContentValues();v.put("id",f.id);v.put("root_uri",f.rootUri);v.put("name",f.name);v.put("path",f.path);v.put("excluded",System.currentTimeMillis());db.insertWithOnConflict("excluded_folders",null,v,SQLiteDatabase.CONFLICT_REPLACE);Object[]a={f.id};db.execSQL("WITH RECURSIVE subtree(id) AS (SELECT ? UNION ALL SELECT x.id FROM folders x JOIN subtree s ON x.parent_id=s.id) DELETE FROM bookmarks WHERE track_uri IN (SELECT uri FROM tracks WHERE folder_id IN (SELECT id FROM subtree))",a);db.execSQL("WITH RECURSIVE subtree(id) AS (SELECT ? UNION ALL SELECT x.id FROM folders x JOIN subtree s ON x.parent_id=s.id) DELETE FROM tracks WHERE folder_id IN (SELECT id FROM subtree)",a);db.execSQL("WITH RECURSIVE subtree(id) AS (SELECT ? UNION ALL SELECT x.id FROM folders x JOIN subtree s ON x.parent_id=s.id) DELETE FROM folders WHERE id IN (SELECT id FROM subtree)",a);db.setTransactionSuccessful();}finally{db.endTransaction();}}
    public boolean isExcluded(String id){try(Cursor c=getReadableDatabase().rawQuery("SELECT 1 FROM excluded_folders WHERE id=?",new String[]{id})){return c.moveToFirst();}}
    public List<String[]> excludedFolders(){ArrayList<String[]>o=new ArrayList<>();try(Cursor c=getReadableDatabase().rawQuery("SELECT id,root_uri,name,path FROM excluded_folders ORDER BY excluded DESC",null)){while(c.moveToNext())o.add(new String[]{c.getString(0),c.getString(1),c.getString(2),c.getString(3)});}return o;}
    public void restoreExcluded(String id){getWritableDatabase().delete("excluded_folders","id=?",new String[]{id});}
    public void restoreExcludedUnderRoot(String rootUri){getWritableDatabase().delete("excluded_folders","root_uri=?",new String[]{rootUri});}
    public void restoreExcludedDocument(String documentId){SQLiteDatabase db=getWritableDatabase();ArrayList<String>matches=new ArrayList<>();try(Cursor c=db.rawQuery("SELECT id FROM excluded_folders",null)){while(c.moveToNext()){String id=c.getString(0);if(FolderIdentity.documentIdFromExcludedKey(id).equals(documentId))matches.add(id);}}for(String id:matches)db.delete("excluded_folders","id=?",new String[]{id});}
    public void clearFolderProgress(String id){SQLiteDatabase db=getWritableDatabase();Object[]a={id};db.execSQL("WITH RECURSIVE subtree(id) AS (SELECT ? UNION ALL SELECT x.id FROM folders x JOIN subtree s ON x.parent_id=s.id) UPDATE tracks SET position=0,completed=0,last_played=0 WHERE folder_id IN (SELECT id FROM subtree)",a);db.execSQL("WITH RECURSIVE subtree(id) AS (SELECT ? UNION ALL SELECT x.id FROM folders x JOIN subtree s ON x.parent_id=s.id) UPDATE folders SET last_played=0 WHERE id IN (SELECT id FROM subtree)",a);}
    public boolean isInSubtree(String ancestorId,String folderId){try(Cursor c=getReadableDatabase().rawQuery("WITH RECURSIVE subtree(id) AS (SELECT ? UNION ALL SELECT x.id FROM folders x JOIN subtree s ON x.parent_id=s.id) SELECT 1 FROM subtree WHERE id=? LIMIT 1",new String[]{ancestorId,folderId})){return c.moveToFirst();}}
    public String playbackProfileId(String folderId){String best=null;for(ScanRoot root:scanRoots())if(isInSubtree(root.id,folderId)&&(best==null||root.id.length()>best.length()))best=root.id;return best==null?folderId:best;}
    public void replaceScan(String rootUri, List<Folder> folders, List<Track> tracks) {
        SQLiteDatabase db=getWritableDatabase(); db.beginTransaction(); try {
            HashSet<String> found=new HashSet<>();
            for(Folder f:folders){found.add(f.id); ContentValues v=new ContentValues();v.put("id",f.id);v.put("root_uri",rootUri);v.put("parent_id",f.parentId);v.put("name",f.name);v.put("path",f.path);v.put("last_scan",System.currentTimeMillis());db.insertWithOnConflict("folders",null,v,SQLiteDatabase.CONFLICT_IGNORE);db.update("folders",v,"id=?",new String[]{f.id});}
            for(Track t:tracks){ContentValues v=new ContentValues();v.put("uri",t.uri);v.put("folder_id",t.folderId);v.put("name",t.name);v.put("title",t.title);v.put("artist",t.artist);v.put("duration",t.duration);v.put("size",t.size);v.put("modified",t.modified);db.insertWithOnConflict("tracks",null,v,SQLiteDatabase.CONFLICT_IGNORE);db.update("tracks",v,"uri=?",new String[]{t.uri});}
            // Remove missing items using exact scan URI set without losing playback state of present files.
            try(Cursor c=db.rawQuery("SELECT uri FROM tracks WHERE folder_id IN (SELECT id FROM folders WHERE root_uri=?)",new String[]{rootUri})){
                HashSet<String> keep=new HashSet<>(); for(Track t:tracks)keep.add(t.uri); while(c.moveToNext())if(!keep.contains(c.getString(0))){String missing=c.getString(0);db.delete("bookmarks","track_uri=?",new String[]{missing});db.delete("tracks","uri=?",new String[]{missing});}
            }
            try(Cursor c=db.rawQuery("SELECT id FROM folders WHERE root_uri=?",new String[]{rootUri})){while(c.moveToNext())if(!found.contains(c.getString(0)))db.delete("folders","id=?",new String[]{c.getString(0)});}
            db.setTransactionSuccessful();
        } finally {db.endTransaction();}
    }
    public void replaceSubtree(String subtreeId,List<Folder> folders,List<Track> tracks){SQLiteDatabase db=getWritableDatabase();db.beginTransaction();try{HashSet<String>oldIds=new HashSet<>(),foundFolders=new HashSet<>(),foundTracks=new HashSet<>();try(Cursor c=db.rawQuery("WITH RECURSIVE subtree(id) AS (SELECT ? UNION ALL SELECT x.id FROM folders x JOIN subtree s ON x.parent_id=s.id) SELECT id FROM subtree",new String[]{subtreeId})){while(c.moveToNext())oldIds.add(c.getString(0));}for(Folder f:folders){foundFolders.add(f.id);ContentValues v=new ContentValues();v.put("id",f.id);v.put("root_uri",f.rootUri);v.put("parent_id",f.parentId);v.put("name",f.name);v.put("path",f.path);v.put("last_scan",System.currentTimeMillis());db.insertWithOnConflict("folders",null,v,SQLiteDatabase.CONFLICT_IGNORE);db.update("folders",v,"id=?",new String[]{f.id});}for(Track t:tracks){foundTracks.add(t.uri);ContentValues v=new ContentValues();v.put("uri",t.uri);v.put("folder_id",t.folderId);v.put("name",t.name);v.put("title",t.title);v.put("artist",t.artist);v.put("duration",t.duration);v.put("size",t.size);v.put("modified",t.modified);db.insertWithOnConflict("tracks",null,v,SQLiteDatabase.CONFLICT_IGNORE);db.update("tracks",v,"uri=?",new String[]{t.uri});}for(String id:oldIds){try(Cursor c=db.rawQuery("SELECT uri FROM tracks WHERE folder_id=?",new String[]{id})){while(c.moveToNext())if(!foundTracks.contains(c.getString(0))){String missing=c.getString(0);db.delete("bookmarks","track_uri=?",new String[]{missing});db.delete("tracks","uri=?",new String[]{missing});}}}for(String id:oldIds)if(!foundFolders.contains(id))db.delete("folders","id=?",new String[]{id});db.setTransactionSuccessful();}finally{db.endTransaction();}}
    public List<Folder> topLevelFolders(){LinkedHashSet<String>ids=new LinkedHashSet<>();ids.add(SampleContent.FOLDER_ID);for(ScanRoot root:scanRoots())ids.add(root.id);ArrayList<Folder>out=new ArrayList<>();for(String id:ids){Folder f=folderSummary(id);if(f!=null&&f.count>0)out.add(f);}sortFolders(out);return out;}
    public List<Folder> childFolders(String parentId){ArrayList<Folder>out=new ArrayList<>();try(Cursor c=getReadableDatabase().rawQuery("SELECT id FROM folders WHERE parent_id=?",new String[]{parentId})){while(c.moveToNext()){Folder f=folderSummary(c.getString(0));if(f!=null&&f.count>0)out.add(f);}}sortFolders(out);return out;}
    public List<Folder> folders(String query){ArrayList<Folder>out=new ArrayList<>();String sql="SELECT id FROM folders";String[]args=null;if(query!=null&&!query.trim().isEmpty()){sql+=" WHERE name LIKE ? OR path LIKE ?";args=new String[]{"%"+query.trim()+"%","%"+query.trim()+"%"};}try(Cursor c=getReadableDatabase().rawQuery(sql,args)){while(c.moveToNext()){Folder f=folderSummary(c.getString(0));if(f!=null&&f.count>0)out.add(f);}}sortFolders(out);return out;}
    public Folder folder(String id){return folderSummary(id);}
    private Folder folderSummary(String id){String sql="WITH RECURSIVE subtree(id) AS (SELECT id FROM folders WHERE id=? UNION ALL SELECT f.id FROM folders f JOIN subtree s ON f.parent_id=s.id) SELECT f.id,f.root_uri,f.parent_id,f.name,f.path,COALESCE(MAX(t.last_played),f.last_played),COUNT(t.uri),COALESCE(SUM(t.duration),0),COALESCE(SUM(t.completed),0) FROM folders f LEFT JOIN tracks t ON t.folder_id IN (SELECT id FROM subtree) WHERE f.id=? GROUP BY f.id";try(Cursor c=getReadableDatabase().rawQuery(sql,new String[]{id,id})){if(!c.moveToFirst())return null;Folder f=new Folder();f.id=c.getString(0);f.rootUri=c.getString(1);f.parentId=c.getString(2);f.name=c.getString(3);f.path=c.getString(4);f.lastPlayed=c.getLong(5);f.count=c.getInt(6);f.totalDuration=c.getLong(7);f.completed=c.getInt(8);return f;}}
    private void sortFolders(List<Folder>folders){folders.sort((a,b)->{int recent=Long.compare(b.lastPlayed,a.lastPlayed);return recent!=0?recent:NaturalOrder.compare(a.path,b.path);});}
    public List<Track> tracks(String folderId, String query, boolean favoritesOnly) {
        ArrayList<Track> out=new ArrayList<>(); ArrayList<String> cond=new ArrayList<>(), args=new ArrayList<>();
        if(folderId!=null){cond.add("folder_id=?");args.add(folderId);} if(query!=null&&!query.isEmpty()){cond.add("(name LIKE ? OR title LIKE ? OR artist LIKE ?)");for(int i=0;i<3;i++)args.add("%"+query+"%");} if(favoritesOnly)cond.add("favorite=1");
        String sql="SELECT t.uri,t.folder_id,t.name,t.title,t.artist,t.duration,t.size,t.modified,t.position,t.completed,t.last_played,t.favorite,f.path FROM tracks t JOIN folders f ON f.id=t.folder_id"+(cond.isEmpty()?"":" WHERE "+String.join(" AND ",prefixTrackConditions(cond)));
        try(Cursor c=getReadableDatabase().rawQuery(sql,args.toArray(new String[0]))){while(c.moveToNext())out.add(readTrack(c));}
        sortTracks(out);return out;
    }
    public List<Track> tracksInSubtree(String folderId,String query,boolean favoritesOnly){ArrayList<String>cond=new ArrayList<>(),args=new ArrayList<>();args.add(folderId);if(query!=null&&!query.trim().isEmpty()){cond.add("(t.name LIKE ? OR t.title LIKE ? OR t.artist LIKE ?)");for(int i=0;i<3;i++)args.add("%"+query.trim()+"%");}if(favoritesOnly)cond.add("t.favorite=1");String sql="WITH RECURSIVE subtree(id) AS (SELECT id FROM folders WHERE id=? UNION ALL SELECT f.id FROM folders f JOIN subtree s ON f.parent_id=s.id) SELECT t.uri,t.folder_id,t.name,t.title,t.artist,t.duration,t.size,t.modified,t.position,t.completed,t.last_played,t.favorite,f.path FROM tracks t JOIN folders f ON f.id=t.folder_id WHERE t.folder_id IN (SELECT id FROM subtree)"+(cond.isEmpty()?"":" AND "+String.join(" AND ",cond));ArrayList<Track>out=new ArrayList<>();try(Cursor c=getReadableDatabase().rawQuery(sql,args.toArray(new String[0]))){while(c.moveToNext())out.add(readTrack(c));}sortTracks(out);return out;}
    private List<String> prefixTrackConditions(List<String>conditions){ArrayList<String>out=new ArrayList<>();for(String condition:conditions){if(condition.equals("folder_id=?"))out.add("t.folder_id=?");else if(condition.equals("favorite=1"))out.add("t.favorite=1");else out.add(condition.replace("name LIKE","t.name LIKE").replace("title LIKE","t.title LIKE").replace("artist LIKE","t.artist LIKE"));}return out;}
    private void sortTracks(List<Track>tracks){tracks.sort((a,b)->{int folder=NaturalOrder.compare(a.folderPath==null?"":a.folderPath,b.folderPath==null?"":b.folderPath);return folder!=0?folder:NaturalOrder.compare(a.name,b.name);});}
    private Track readTrack(Cursor c){Track t=new Track();t.uri=c.getString(0);t.folderId=c.getString(1);t.name=c.getString(2);t.title=c.getString(3);t.artist=c.getString(4);t.duration=c.getLong(5);t.size=c.getLong(6);t.modified=c.getLong(7);t.position=c.getLong(8);t.completed=c.getInt(9)!=0;t.lastPlayed=c.getLong(10);t.favorite=c.getInt(11)!=0;if(c.getColumnCount()>12)t.folderPath=c.getString(12);return t;}
    public Track track(String uri){try(Cursor c=getReadableDatabase().rawQuery("SELECT uri,folder_id,name,title,artist,duration,size,modified,position,completed,last_played,favorite FROM tracks WHERE uri=?",new String[]{uri})){return c.moveToFirst()?readTrack(c):null;}}
    public Track lastPlayed(){try(Cursor c=getReadableDatabase().rawQuery("SELECT uri,folder_id,name,title,artist,duration,size,modified,position,completed,last_played,favorite FROM tracks WHERE last_played>0 ORDER BY last_played DESC LIMIT 1",null)){return c.moveToFirst()?readTrack(c):null;}}
    public Track lastPlayedInSubtree(String folderId){String sql="WITH RECURSIVE subtree(id) AS (SELECT id FROM folders WHERE id=? UNION ALL SELECT f.id FROM folders f JOIN subtree s ON f.parent_id=s.id) SELECT t.uri,t.folder_id,t.name,t.title,t.artist,t.duration,t.size,t.modified,t.position,t.completed,t.last_played,t.favorite,f.path FROM tracks t JOIN folders f ON f.id=t.folder_id WHERE t.folder_id IN (SELECT id FROM subtree) AND t.last_played>0 ORDER BY t.last_played DESC LIMIT 1";try(Cursor c=getReadableDatabase().rawQuery(sql,new String[]{folderId})){return c.moveToFirst()?readTrack(c):null;}}
    public String directChildToward(String ancestorId,String descendantId){if(ancestorId.equals(descendantId))return null;String sql="WITH RECURSIVE chain(id,parent_id) AS (SELECT id,parent_id FROM folders WHERE id=? UNION ALL SELECT f.id,f.parent_id FROM folders f JOIN chain c ON c.parent_id=f.id) SELECT id FROM chain WHERE parent_id=? LIMIT 1";try(Cursor c=getReadableDatabase().rawQuery(sql,new String[]{descendantId,ancestorId})){return c.moveToFirst()?c.getString(0):null;}}
    public void saveProgress(String uri,long pos,long duration,boolean complete){ContentValues v=new ContentValues();v.put("position",complete?duration:Math.max(0,pos));v.put("duration",duration);v.put("completed",complete?1:0);v.put("last_played",System.currentTimeMillis());getWritableDatabase().update("tracks",v,"uri=?",new String[]{uri});getWritableDatabase().execSQL("UPDATE folders SET last_played=? WHERE id=(SELECT folder_id FROM tracks WHERE uri=?)",new Object[]{System.currentTimeMillis(),uri});}
    public void setCompleted(String uri,boolean done){if(done)getWritableDatabase().execSQL("UPDATE tracks SET completed=1,position=duration WHERE uri=?",new Object[]{uri});else{ContentValues v=new ContentValues();v.put("completed",0);v.put("position",0);getWritableDatabase().update("tracks",v,"uri=?",new String[]{uri});}}
    public void toggleFavorite(String uri){getWritableDatabase().execSQL("UPDATE tracks SET favorite=CASE favorite WHEN 0 THEN 1 ELSE 0 END WHERE uri=?",new Object[]{uri});}
    public void addBookmark(String uri,long position,String note){ContentValues v=new ContentValues();v.put("track_uri",uri);v.put("position",position);v.put("note",note);v.put("created",System.currentTimeMillis());getWritableDatabase().insert("bookmarks",null,v);}
    public List<String[]> bookmarks(String uri){ArrayList<String[]>o=new ArrayList<>();try(Cursor c=getReadableDatabase().rawQuery("SELECT id,position,note FROM bookmarks WHERE track_uri=? ORDER BY position",new String[]{uri})){while(c.moveToNext())o.add(new String[]{c.getString(0),c.getString(1),c.getString(2)});}return o;}
    public String setting(String key,String fallback){try(Cursor c=getReadableDatabase().rawQuery("SELECT value FROM settings WHERE key=?",new String[]{key})){return c.moveToFirst()?c.getString(0):fallback;}}
    public void setSetting(String key,String value){ContentValues v=new ContentValues();v.put("key",key);v.put("value",value);getWritableDatabase().insertWithOnConflict("settings",null,v,SQLiteDatabase.CONFLICT_REPLACE);}
}
