package com.matianju.fm;

import android.Manifest;
import android.annotation.SuppressLint;
import android.app.*;
import android.content.*;
import android.content.pm.PackageManager;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.os.*;
import android.provider.DocumentsContract;
import android.text.TextUtils;
import android.view.*;
import android.view.inputmethod.EditorInfo;
import android.widget.*;
import java.text.*;
import java.util.*;
import java.util.regex.*;

@SuppressLint("SetTextI18n")
public final class MainActivity extends Activity {
    private static final int PICK_TREE=40; private final int INK=Color.rgb(23,34,45),PAPER=Color.rgb(246,243,236),GREEN=Color.rgb(23,107,91),AMBER=Color.rgb(228,154,66),MUTED=Color.rgb(105,113,118);
    private LibraryDb db; private FolderScanner scanner; private PlayerService service; private boolean bound=false,scanning=false,pickingFolder=false,returnToPlayerFromDirectory=false; private FrameLayout page; private LinearLayout mini; private TextView miniTitle,miniState; private String openFolder=null; private final Handler ui=new Handler(Looper.getMainLooper());
    private final Runnable refresh=new Runnable(){public void run(){refreshMini();if(page!=null&&"player".equals(page.getTag()))refreshPlayerFields();ui.postDelayed(this,500);}};
    private TextView playerTitle,playerSubtitle,playerEpisode,elapsed,total; private SeekBar seek; private Button playButton,speedButton,sleepButton,skipButton;
    private final ServiceConnection connection=new ServiceConnection(){public void onServiceConnected(ComponentName n,android.os.IBinder b){service=((PlayerService.LocalBinder)b).service();bound=true;refreshMini();}public void onServiceDisconnected(ComponentName n){bound=false;service=null;}};

    @Override public void onCreate(Bundle state){super.onCreate(state);db=LibraryDb.get(this);SampleContent.ensure(this);db.scanRoots();scanner=new FolderScanner(this);getWindow().setStatusBarColor(PAPER);getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR);buildShell();showHome();bindService(new Intent(this,PlayerService.class),connection,BIND_AUTO_CREATE);if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},5);ui.post(refresh);}
    @Override protected void onDestroy(){ui.removeCallbacks(refresh);if(bound)unbindService(connection);super.onDestroy();}
    @Override public void onBackPressed(){if(returnToPlayerFromDirectory&&"folder".equals(page.getTag())){returnToPlayerFromDirectory=false;showPlayer();}else if("player".equals(page.getTag())){if(openFolder!=null)showFolder(openFolder);else showHome();}else if(openFolder!=null){LibraryDb.Folder f=db.folder(openFolder);if(f!=null&&f.parentId!=null&&db.folder(f.parentId)!=null)showFolder(f.parentId);else showHome();}else super.onBackPressed();}

    private void buildShell(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(PAPER);root.setOnApplyWindowInsetsListener((v,insets)->{v.setPadding(0,insets.getSystemWindowInsetTop(),0,0);return insets;});page=new FrameLayout(this);root.addView(page,new LinearLayout.LayoutParams(-1,0,1));mini=new LinearLayout(this);mini.setOrientation(LinearLayout.VERTICAL);mini.setPadding(dp(14),dp(8),dp(14),dp(8));mini.setBackgroundColor(INK);mini.setVisibility(View.GONE);
        LinearLayout meta=new LinearLayout(this);meta.setGravity(Gravity.CENTER_VERTICAL);miniTitle=label("",15,Color.WHITE,true);miniTitle.setSingleLine(true);miniTitle.setEllipsize(TextUtils.TruncateAt.END);miniState=label("",12,Color.WHITE,false);miniState.setSingleLine(true);meta.addView(miniTitle,new LinearLayout.LayoutParams(0,dp(28),1));meta.addView(miniState);mini.addView(meta,new LinearLayout.LayoutParams(-1,dp(30)));
        LinearLayout controls=new LinearLayout(this);controls.setGravity(Gravity.CENTER);TextView previous=miniControl("上一首",false);previous.setOnClickListener(v->{if(bound)service.previous();});TextView back=miniControl("−15 秒",false);back.setOnClickListener(v->{if(bound)service.skip(-15000);});TextView toggle=miniControl("播放",true);toggle.setTag("miniPlay");toggle.setOnClickListener(v->{if(bound)service.toggle();});TextView forward=miniControl("+15 秒",false);forward.setOnClickListener(v->{if(bound)service.skip(15000);});TextView next=miniControl("下一首",false);next.setOnClickListener(v->{if(bound)service.next();});controls.addView(previous);controls.addView(back);controls.addView(toggle);controls.addView(forward);controls.addView(next);mini.addView(controls,new LinearLayout.LayoutParams(-1,dp(46)));meta.setOnClickListener(v->showPlayer());root.addView(mini);setContentView(root);root.requestApplyInsets();}
    private TextView miniControl(String text,boolean primary){TextView v=label(text,13,primary?INK:Color.WHITE,true);v.setGravity(Gravity.CENTER);v.setBackground(primary?round(AMBER,18):round(Color.TRANSPARENT,18));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(40),1);p.setMargins(dp(2),dp(2),dp(2),dp(2));v.setLayoutParams(p);return v;}
    private void setPage(View v,String tag){page.removeAllViews();page.setTag(tag);page.addView(v,new FrameLayout.LayoutParams(-1,-1));refreshMini();}

    private void showHome(){openFolder=null;ScrollView scroll=new ScrollView(this);LinearLayout body=column(dp(20));body.setPadding(dp(20),dp(16),dp(20),dp(36));
        LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);LinearLayout brand=column(0);brand.addView(label("马天驹 FM",28,INK,true));brand.addView(label(scanning?"正在扫描，请稍候…":"把文件夹听完",13,scanning?AMBER:MUTED,false));head.addView(brand,new LinearLayout.LayoutParams(0,-2,1));Button add=button(scanning?"扫描中":"＋ 添加文件夹");stylePrimary(add);add.setEnabled(!scanning&&!pickingFolder);add.setAlpha(add.isEnabled()?1f:.55f);add.setOnClickListener(v->pickFolder());head.addView(add);body.addView(head);
        SearchView search=new SearchView(this);search.setQueryHint("搜索文件夹或音频");search.setIconifiedByDefault(false);search.setBackground(round(Color.WHITE,14));LinearLayout.LayoutParams sp=lp(-1,dp(52));sp.setMargins(0,dp(20),0,dp(18));body.addView(search,sp);search.setOnQueryTextListener(new SearchView.OnQueryTextListener(){public boolean onQueryTextSubmit(String q){showSearch(q);return true;}public boolean onQueryTextChange(String q){return false;}});
        LibraryDb.Track last=db.lastPlayed();body.addView(sectionTitle("继续播放"));if(last==null)body.addView(infoCard("还没有播放记录","添加文件夹并选择一段音频后，这里会记住进度。"));else body.addView(continueCard(last));
        LinearLayout sectionHead=new LinearLayout(this);sectionHead.setGravity(Gravity.CENTER_VERTICAL);sectionHead.addView(sectionTitle("我的文件夹"),new LinearLayout.LayoutParams(0,-2,1));if(!db.excludedFolders().isEmpty()){Button excluded=button("已移出");excluded.setTextColor(MUTED);excluded.setOnClickListener(v->showExcludedFolders());sectionHead.addView(excluded);}Button scan=button("重新扫描");scan.setTextColor(GREEN);scan.setOnClickListener(v->rescan());sectionHead.addView(scan);body.addView(sectionHead);
        List<LibraryDb.Folder> folders=db.topLevelFolders();if(folders.isEmpty())body.addView(emptyLibrary());else for(LibraryDb.Folder f:folders)body.addView(folderCard(f));
        List<LibraryDb.Track> fav=db.tracks(null,null,true);if(!fav.isEmpty()){body.addView(sectionTitle("收藏 · "+fav.size()));for(int i=0;i<Math.min(3,fav.size());i++)body.addView(trackRow(fav.get(i),fav,i,false));}
        body.addView(privacyCard());scroll.addView(body);setPage(scroll,"home");}
    private View emptyLibrary(){LinearLayout card=card();TextView icon=label("♫",42,GREEN,true);icon.setGravity(Gravity.CENTER);card.addView(icon);TextView t=label("还没有本地音频",19,INK,true);t.setGravity(Gravity.CENTER);card.addView(t);TextView d=label("选择包含课程、录音、有声书或播客的文件夹。音频只在本机读取，不会上传。",14,MUTED,false);d.setGravity(Gravity.CENTER);d.setPadding(dp(10),dp(8),dp(10),dp(16));card.addView(d);Button b=button("选择文件夹");stylePrimary(b);b.setOnClickListener(v->pickFolder());card.addView(b,new LinearLayout.LayoutParams(-1,dp(48)));return card;}
    private View privacyCard(){TextView v=label("🔒  全部本地处理 · 不上传音频文件",13,GREEN,true);v.setPadding(dp(14),dp(18),dp(14),dp(10));return v;}
    private View continueCard(LibraryDb.Track t){String profile=db.playbackProfileId(t.folderId);List<LibraryDb.Track>queue=db.tracksInSubtree(profile,null,false);LinearLayout c=card();c.setOnClickListener(v->openTrack(t,queue));c.addView(label(t.displayTitle(),18,INK,true));LibraryDb.Folder f=db.folder(profile);c.addView(label((f==null?"本地音频":f.name)+"  ·  "+format(t.position)+" / "+format(t.duration),13,MUTED,false));ProgressBar p=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);p.setMax(1000);p.setProgress(t.duration>0?(int)(t.position*1000/t.duration):0);LinearLayout.LayoutParams pp=lp(-1,dp(8));pp.setMargins(0,dp(12),0,0);c.addView(p,pp);Button b=button("继续播放  →");b.setTextColor(GREEN);b.setOnClickListener(v->openTrack(t,queue));c.addView(b);return c;}
    private View folderCard(LibraryDb.Folder f){LinearLayout c=card();c.setTag("folder:"+f.id);c.setOnClickListener(v->showFolder(f.id));LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);TextView icon=label("▤",25,GREEN,true);icon.setGravity(Gravity.CENTER);icon.setBackground(round(Color.rgb(223,236,230),12));row.addView(icon,new LinearLayout.LayoutParams(dp(48),dp(48)));LinearLayout texts=column(0);texts.setPadding(dp(14),0,0,0);texts.addView(label(f.name,17,INK,true));texts.addView(label(f.count+" 个音频 · "+format(f.totalDuration)+(f.path.equals(f.name)?"":"\n"+f.path),12,MUTED,false));row.addView(texts,new LinearLayout.LayoutParams(0,-2,1));TextView more=label("⋮",24,MUTED,true);more.setGravity(Gravity.CENTER);more.setOnClickListener(v->folderMenu(f));row.addView(more,new LinearLayout.LayoutParams(dp(44),dp(48)));c.addView(row);ProgressBar p=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);p.setMax(Math.max(1,f.count));p.setProgress(f.completed);LinearLayout.LayoutParams pp=lp(-1,dp(5));pp.setMargins(0,dp(12),0,0);c.addView(p,pp);c.addView(label(f.completed+" / "+f.count+" 已听完",11,MUTED,false));return c;}

    private void showFolder(String id){showFolder(id,null);}
    private void showFolder(String id,String exactTrackUri){LibraryDb.Folder f=db.folder(id);if(f==null)return;openFolder=id;LinearLayout root=column(0);root.setPadding(dp(18),dp(12),dp(18),0);LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);Button back=button("‹");back.setTextSize(28);back.setOnClickListener(v->{if(returnToPlayerFromDirectory){returnToPlayerFromDirectory=false;showPlayer();}else if(f.parentId!=null&&db.folder(f.parentId)!=null)showFolder(f.parentId);else showHome();});head.addView(back);LinearLayout title=column(0);title.addView(label(f.name,23,INK,true));title.addView(label(f.count+" 个音频（含子文件夹） · "+format(f.totalDuration),12,MUTED,false));head.addView(title,new LinearLayout.LayoutParams(0,-2,1));Button menu=button("⋮");menu.setTextSize(23);menu.setOnClickListener(v->folderMenu(f));head.addView(menu,new LinearLayout.LayoutParams(dp(44),dp(44)));Button play=button("全部播放");stylePrimary(play);head.addView(play);root.addView(head);
        SearchView search=new SearchView(this);search.setIconifiedByDefault(false);search.setQueryHint("搜索这个合集及全部子文件夹");search.setBackground(round(Color.WHITE,14));LinearLayout.LayoutParams slp=lp(-1,dp(50));slp.setMargins(0,dp(14),0,dp(10));root.addView(search,slp);
        ScrollView scroll=new ScrollView(this);LinearLayout list=column(dp(8));renderFolderContents(list,id,"");scroll.addView(list);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));List<LibraryDb.Track>allTracks=db.tracksInSubtree(id,null,false);play.setOnClickListener(v->{if(!allTracks.isEmpty())startTrack(allTracks,0,false);});search.setOnQueryTextListener(new SearchView.OnQueryTextListener(){public boolean onQueryTextSubmit(String q){return true;}public boolean onQueryTextChange(String q){renderFolderContents(list,id,q);return true;}});setPage(root,"folder");if(exactTrackUri==null)scrollToLastPlayed(scroll,list,id);else scrollToTrack(scroll,list,exactTrackUri);}
    private void scrollToTrack(ScrollView scroll,LinearLayout list,String trackUri){String anchor="track:"+trackUri;scroll.post(()->{View target=list.findViewWithTag(anchor);if(target!=null)scroll.scrollTo(0,Math.max(0,target.getTop()-Math.max(dp(10),scroll.getHeight()/3)));});}
    private void scrollToLastPlayed(ScrollView scroll,LinearLayout list,String folderId){LibraryDb.Track recent=db.lastPlayedInSubtree(folderId);if(recent==null)return;String anchor;if(folderId.equals(recent.folderId))anchor="track:"+recent.uri;else{String child=db.directChildToward(folderId,recent.folderId);if(child==null)return;anchor="folder:"+child;}scroll.post(()->{View target=list.findViewWithTag(anchor);if(target!=null)scroll.scrollTo(0,Math.max(0,target.getTop()-dp(10)));});}
    private void renderFolderContents(LinearLayout list,String folderId,String query){list.removeAllViews();String q=query==null?"":query.trim();if(q.isEmpty()){List<LibraryDb.Folder>children=db.childFolders(folderId);if(!children.isEmpty()){list.addView(sectionTitle("子文件夹 · "+children.size()));for(LibraryDb.Folder child:children)list.addView(folderCard(child));}List<LibraryDb.Track>direct=db.tracks(folderId,null,false);if(!direct.isEmpty()){list.addView(sectionTitle("当前文件夹音频 · "+direct.size()));List<LibraryDb.Track>queue=db.tracksInSubtree(folderId,null,false);for(int i=0;i<direct.size();i++)list.addView(trackRow(direct.get(i),queue,indexOf(queue,direct.get(i).uri),true));}if(children.isEmpty()&&direct.isEmpty())list.addView(infoCard("没有找到音频","这个文件夹及其子文件夹中没有可识别的音频文件。"));return;}List<LibraryDb.Track>matches=db.tracksInSubtree(folderId,q,false);list.addView(sectionTitle("搜索结果 · "+matches.size()));for(int i=0;i<matches.size();i++)list.addView(trackRow(matches.get(i),matches,i,true));if(matches.isEmpty())list.addView(infoCard("没有找到","请尝试其他文件名或音频标签。"));}
    private void folderMenu(LibraryDb.Folder f){String[]items={"移出资料库","重新扫描此目录","清除全部播放记录"};new AlertDialog.Builder(this).setTitle(f.name).setItems(items,(d,w)->{if(w==0)confirmRemoveFolder(f);else if(w==1)rescanFolder(f);else confirmClearFolderProgress(f);}).setNegativeButton("取消",null).show();}
    private void confirmRemoveFolder(LibraryDb.Folder f){boolean sample=SampleContent.isSample(f),root=!sample&&db.isScanRoot(f.id);String message=sample?"将删除 App 本地示例目录中的试听音频，今后启动时不会自动恢复。":root?"将从马天驹 FM 移除这个已添加目录。只有没有其他目录共用授权时，才会同时释放读取权限。手机里的音频文件不会被删除。":"将从马天驹 FM 移除此合集及其子目录。它会进入排除名单，重新扫描也不会自动出现。手机里的音频文件不会被删除。";new AlertDialog.Builder(this).setTitle("移出“"+f.name+"”？").setMessage(message).setPositiveButton("移出资料库",(d,w)->{stopIfPlayingIn(f);if(sample)SampleContent.remove(this);else if(root){boolean release=db.removeScanRoot(f.id);if(release)try{getContentResolver().releasePersistableUriPermission(Uri.parse(f.rootUri),Intent.FLAG_GRANT_READ_URI_PERMISSION);}catch(Exception ignored){}}else db.excludeFolder(f);openFolder=null;Toast.makeText(this,sample?"内置示例已删除":"已移出资料库，本地文件未删除",Toast.LENGTH_LONG).show();showHome();}).setNegativeButton("取消",null).show();}
    private void confirmClearFolderProgress(LibraryDb.Folder f){new AlertDialog.Builder(this).setTitle("清除全部播放记录？").setMessage("将清除“"+f.name+"”及其子目录中所有音频的播放位置、已听状态和最近播放时间。收藏、书签和本地文件不受影响。").setPositiveButton("确认清除",(d,w)->{stopIfPlayingIn(f);db.clearFolderProgress(f.id);Toast.makeText(this,"播放记录已清除",Toast.LENGTH_SHORT).show();showFolder(f.id);}).setNegativeButton("取消",null).show();}
    private void stopIfPlayingIn(LibraryDb.Folder f){if(bound&&service.current()!=null&&db.isInSubtree(f.id,service.current().folderId))service.stopAndClear();}
    private void rescanFolder(LibraryDb.Folder f){if(SampleContent.isSample(f)){SampleContent.ensure(this);Toast.makeText(this,"内置示例无需扫描",Toast.LENGTH_SHORT).show();showFolder(f.id);return;}if(scanning){Toast.makeText(this,"当前扫描尚未完成",Toast.LENGTH_SHORT).show();return;}beginScan();scanner.scanFolder(f,scanCallback());}
    private void showExcludedFolders(){List<String[]>items=db.excludedFolders();if(items.isEmpty()){Toast.makeText(this,"没有已移出的目录",Toast.LENGTH_SHORT).show();return;}String[]labels=new String[items.size()];for(int i=0;i<items.size();i++)labels[i]=items.get(i)[2]+"\n"+items.get(i)[3];new AlertDialog.Builder(this).setTitle("已移出目录").setItems(labels,(d,w)->{String[]x=items.get(w);new AlertDialog.Builder(this).setTitle("恢复“"+x[2]+"”？").setMessage("恢复后将重新扫描它所属的已添加目录。").setPositiveButton("恢复",(d2,w2)->{db.restoreExcluded(x[0]);if(db.scanRoots().isEmpty()){Toast.makeText(this,"原授权文件夹已不存在，请重新添加",Toast.LENGTH_LONG).show();showHome();}else rescan();}).setNegativeButton("取消",null).show();}).setNegativeButton("关闭",null).show();}
    private View trackRow(LibraryDb.Track t,List<LibraryDb.Track> queue,int index,boolean menu){boolean current=bound&&service.current()!=null&&t.uri.equals(service.current().uri);LinearLayout row=new LinearLayout(this);row.setTag("track:"+t.uri);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(dp(12),dp(10),dp(8),dp(10));row.setBackground(round(current?Color.rgb(228,239,234):Color.WHITE,12));TextView status=label(current?"▶":t.completed?"✓":t.position>0?"▶":"○",16,current?GREEN:t.completed?GREEN:AMBER,true);status.setGravity(Gravity.CENTER);row.addView(status,new LinearLayout.LayoutParams(dp(36),dp(42)));LinearLayout text=column(0);text.addView(label(t.displayTitle(),15,INK,true));String detail=format(t.duration);if(current)detail="正在播放 · "+format(t.position)+" / "+detail;else if(t.position>0&&!t.completed)detail="听到 "+format(t.position)+" · "+detail;if(t.completed)detail="已听完 · "+detail;text.addView(label(detail,12,current?GREEN:MUTED,current));row.addView(text,new LinearLayout.LayoutParams(0,-2,1));TextView more=label(t.favorite?"★":"⋮",22,t.favorite?AMBER:MUTED,true);more.setGravity(Gravity.CENTER);row.addView(more,new LinearLayout.LayoutParams(dp(42),dp(42)));row.setOnClickListener(v->openTrack(t,queue));more.setOnClickListener(v->trackMenu(t));LinearLayout.LayoutParams rp=lp(-1,-2);rp.setMargins(0,0,0,dp(7));row.setLayoutParams(rp);return row;}
    private void trackMenu(LibraryDb.Track t){String[] items={t.favorite?"取消收藏":"收藏",t.completed?"标记为未听":"标记为已听","清除播放进度"};new AlertDialog.Builder(this).setTitle(t.displayTitle()).setItems(items,(d,w)->{if(w==0)db.toggleFavorite(t.uri);else if(w==1)db.setCompleted(t.uri,!t.completed);else db.saveProgress(t.uri,0,t.duration,false);if(openFolder!=null)showFolder(openFolder);else showHome();}).show();}

    private void showSearch(String q){LinearLayout root=column(dp(8));root.setPadding(dp(18),dp(12),dp(18),0);LinearLayout head=new LinearLayout(this);Button back=button("‹ 返回");back.setOnClickListener(v->showHome());head.addView(back);head.addView(label("搜索“"+q+"”",22,INK,true));root.addView(head);ScrollView s=new ScrollView(this);LinearLayout list=column(dp(8));for(LibraryDb.Folder f:db.folders(q))list.addView(folderCard(f));List<LibraryDb.Track> tracks=db.tracks(null,q,false);for(int i=0;i<tracks.size();i++)list.addView(trackRow(tracks.get(i),db.tracks(tracks.get(i).folderId,null,false),0,true));if(list.getChildCount()==0)list.addView(infoCard("没有找到","请尝试文件名、文件夹名或音频标签。"));s.addView(list);root.addView(s,new LinearLayout.LayoutParams(-1,0,1));setPage(root,"search");}

    private void openTrack(LibraryDb.Track t,List<LibraryDb.Track> queue){if(t.position>0&&!t.completed){new AlertDialog.Builder(this).setTitle("继续上次播放？").setMessage(t.displayTitle()+"\n上次听到 "+format(t.position)).setPositiveButton("继续播放",(d,w)->startTrack(queue,indexOf(queue,t.uri),false)).setNegativeButton("从头播放",(d,w)->startTrack(queue,indexOf(queue,t.uri),true)).show();}else startTrack(queue,indexOf(queue,t.uri),true);}
    private int indexOf(List<LibraryDb.Track> q,String uri){for(int i=0;i<q.size();i++)if(q.get(i).uri.equals(uri))return i;return 0;}
    private void startTrack(List<LibraryDb.Track> queue,int at,boolean fromStart){if(!bound){Toast.makeText(this,"播放服务正在启动，请再试一次",Toast.LENGTH_SHORT).show();return;}if(queue.isEmpty())return;returnToPlayerFromDirectory=false;if(fromStart){LibraryDb.Track t=queue.get(at);db.saveProgress(t.uri,0,t.duration,false);t.position=0;}startService(new Intent(this,PlayerService.class));service.loadQueue(queue,at,true);String profile=db.playbackProfileId(queue.get(at).folderId);float saved=Float.parseFloat(db.setting("speed_"+profile,"1.0"));service.setSpeed(saved);showPlayer();}

    private void showPlayer(){if(!bound||service.current()==null){Toast.makeText(this,"还没有正在播放的音频",Toast.LENGTH_SHORT).show();return;}ScrollView screen=new ScrollView(this);screen.setFillViewport(true);LinearLayout root=column(0);root.setPadding(dp(20),dp(8),dp(20),dp(6));
        LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER);LinearLayout heading=column(0);TextView headingTitle=label("正在播放",18,INK,true);headingTitle.setGravity(Gravity.CENTER);TextView headingSub=label("本地有声内容",11,MUTED,false);headingSub.setGravity(Gravity.CENTER);heading.addView(headingTitle);heading.addView(headingSub);top.addView(heading,new LinearLayout.LayoutParams(-1,-2));root.addView(top,new LinearLayout.LayoutParams(-1,dp(44)));Space upperSpacer=new Space(this);root.addView(upperSpacer,new LinearLayout.LayoutParams(-1,0,.30f));

        LinearLayout cover=column(0);cover.setGravity(Gravity.CENTER);cover.setPadding(dp(18),dp(18),dp(18),dp(18));cover.setBackground(playerCoverBackground());playerEpisode=label("当前集",30,Color.WHITE,true);playerEpisode.setGravity(Gravity.CENTER);cover.addView(playerEpisode);TextView coverBrand=label("马天驹 FM  ·  本地听书",13,Color.rgb(222,239,234),false);coverBrand.setGravity(Gravity.CENTER);coverBrand.setPadding(0,dp(10),0,0);cover.addView(coverBrand);LinearLayout.LayoutParams coverParams=lp(-1,dp(188));coverParams.setMargins(0,dp(14),0,dp(12));root.addView(cover,coverParams);Space titleSpacer=new Space(this);root.addView(titleSpacer,new LinearLayout.LayoutParams(-1,0,.15f));

        playerTitle=label("",22,INK,true);playerTitle.setGravity(Gravity.CENTER);playerTitle.setMaxLines(3);playerTitle.setEllipsize(TextUtils.TruncateAt.END);root.addView(playerTitle,lp(-1,-2));playerSubtitle=label("",13,MUTED,false);playerSubtitle.setGravity(Gravity.CENTER);playerSubtitle.setPadding(0,dp(9),0,0);root.addView(playerSubtitle,lp(-1,-2));Space controlsSpacer=new Space(this);root.addView(controlsSpacer,new LinearLayout.LayoutParams(-1,0,.55f));

        LinearLayout listeningTools=new LinearLayout(this);listeningTools.setGravity(Gravity.CENTER);Button minus=toolButton("↶\n后退 15 秒");minus.setOnClickListener(v->service.skip(-15000));speedButton=toolButton("1.0×\n倍速");speedButton.setOnClickListener(v->speedDialog());skipButton=toolButton("片头 / 片尾\n0 / 0 秒");skipButton.setOnClickListener(v->skipDialog());Button plus=toolButton("↷\n前进 15 秒");plus.setOnClickListener(v->service.skip(15000));listeningTools.addView(minus);listeningTools.addView(speedButton);listeningTools.addView(skipButton);listeningTools.addView(plus);LinearLayout.LayoutParams toolParams=lp(-1,dp(68));toolParams.setMargins(0,dp(8),0,0);root.addView(listeningTools,toolParams);

        LinearLayout progress=column(0);seek=new SeekBar(this);seek.setMax(1000);seek.setThumb(seekThumb());seek.setThumbOffset(dp(11));seek.setProgressTintList(android.content.res.ColorStateList.valueOf(GREEN));seek.setProgressBackgroundTintList(android.content.res.ColorStateList.valueOf(Color.rgb(194,199,196)));seek.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onProgressChanged(SeekBar s,int p,boolean user){}public void onStartTrackingTouch(SeekBar s){}public void onStopTrackingTouch(SeekBar s){if(bound)service.seekTo(service.duration()*s.getProgress()/1000);}});progress.addView(seek,lp(-1,dp(50)));LinearLayout times=new LinearLayout(this);elapsed=label("0:00",13,INK,true);total=label("0:00",13,MUTED,false);times.addView(elapsed,new LinearLayout.LayoutParams(0,-2,1));times.addView(total);progress.addView(times);LinearLayout.LayoutParams progressParams=lp(-1,dp(78));progressParams.setMargins(0,dp(10),0,0);root.addView(progress,progressParams);

        LinearLayout mainControls=new LinearLayout(this);mainControls.setGravity(Gravity.CENTER);Button directory=playerNavButton("≡▶","目录");directory.setOnClickListener(v->openCurrentDirectory());Button prev=playerNavButton("│◀","上一首");prev.setOnClickListener(v->service.previous());playButton=roundControl("Ⅱ\n暂停",true);playButton.setOnClickListener(v->service.toggle());Button next=playerNavButton("▶│","下一首");next.setOnClickListener(v->service.next());sleepButton=timerButton();sleepButton.setOnClickListener(v->sleepDialog());mainControls.addView(directory);mainControls.addView(prev);mainControls.addView(playButton);mainControls.addView(next);mainControls.addView(sleepButton);LinearLayout.LayoutParams mainParams=lp(-1,dp(96));mainParams.setMargins(0,dp(18),0,0);root.addView(mainControls,mainParams);
        screen.addView(root);setPage(screen,"player");refreshPlayerFields();}
    private void openCurrentDirectory(){if(!bound||service.current()==null)return;LibraryDb.Track current=service.current();returnToPlayerFromDirectory=true;showFolder(current.folderId,current.uri);}
    private Button roundControl(String text,boolean main){Button b=button(text);b.setTextColor(main?Color.WHITE:INK);b.setTextSize(15);b.setBackground(round(main?GREEN:Color.TRANSPARENT,50));b.setAllCaps(false);b.setPadding(dp(5),0,dp(5),0);b.setMinWidth(0);b.setMinimumWidth(0);LinearLayout.LayoutParams p=lp(dp(76),dp(76));p.setMargins(dp(3),0,dp(3),0);b.setLayoutParams(p);return b;}
    private Button playerNavButton(String icon,String caption){Button b=button(icon+"\n"+caption);b.setTextSize(12);b.setTypeface(Typeface.create("sans",Typeface.NORMAL));b.setTextColor(INK);b.setGravity(Gravity.CENTER);b.setMinWidth(0);b.setMinimumWidth(0);b.setPadding(dp(2),0,dp(2),0);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(70),1);p.setMargins(dp(1),0,dp(1),0);b.setLayoutParams(p);return b;}
    private Button timerButton(){return playerNavButton("◴","定时");}
    private Button toolButton(String text){Button b=button(text);b.setTextSize(11);b.setTextColor(GREEN);b.setGravity(Gravity.CENTER);b.setBackground(round(Color.rgb(231,240,235),14));b.setMinWidth(0);b.setMinimumWidth(0);b.setPadding(dp(2),0,dp(2),0);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(56),1);p.setMargins(dp(3),dp(5),dp(3),0);b.setLayoutParams(p);return b;}
    private GradientDrawable seekThumb(){GradientDrawable g=new GradientDrawable();g.setShape(GradientDrawable.OVAL);g.setColor(GREEN);g.setSize(dp(22),dp(22));return g;}
    private GradientDrawable playerCoverBackground(){GradientDrawable g=new GradientDrawable(GradientDrawable.Orientation.TL_BR,new int[]{Color.rgb(19,118,97),Color.rgb(14,72,76)});g.setCornerRadius(dp(24));return g;}
    private void refreshPlayerFields(){if(!bound||service.current()==null||playerTitle==null)return;LibraryDb.Track t=db.track(service.current().uri);if(t==null)t=service.current();playerEpisode.setText(episodeLabel(t.name));playerTitle.setText(t.displayTitle());LibraryDb.Folder f=db.folder(t.folderId);playerSubtitle.setText((f==null?"本地音频":f.name)+" · 顺序播放");long pos=service.position(),dur=service.duration();elapsed.setText(format(pos));total.setText(format(dur));seek.setProgress(dur>0?(int)(pos*1000/dur):0);playButton.setText(service.isPlaying()?"Ⅱ\n暂停":"▶\n播放");speedButton.setText(trimSpeed(service.speed())+"×\n倍速");skipButton.setText("片头 / 片尾\n"+(service.introSkip()/1000)+" / "+(service.outroSkip()/1000)+" 秒");long rem=service.sleepRemaining();sleepButton.setText(rem>0?"◴\n"+((rem+59999)/60000)+"分":service.sleepAfterTrackEnabled()?"◴\n本集后":"◴\n定时");}
    private String episodeLabel(String name){Matcher m=Pattern.compile("(?<!\\d)(\\d{1,6})(?!\\d)").matcher(name==null?"":name);if(!m.find())return "当前集";try{return "第 "+Long.parseLong(m.group(1))+" 集";}catch(Exception ignored){return "第 "+m.group(1)+" 集";}}
    private void speedDialog(){String[] values={"0.5×","0.75×","1.0×","1.25×","1.5×","1.75×","2.0×","2.5×","3.0×","自定义"};new AlertDialog.Builder(this).setTitle("播放速度（按合集记忆）").setItems(values,(d,w)->{if(w<9)service.setSpeed(Float.parseFloat(values[w].replace("×","")));else customSpeed();refreshPlayerFields();}).show();}
    private void customSpeed(){final EditText e=new EditText(this);e.setInputType(2|8192);e.setHint("0.5 到 3.0");new AlertDialog.Builder(this).setTitle("自定义倍速").setView(e).setPositiveButton("确定",(d,w)->{try{float x=Float.parseFloat(e.getText().toString());service.setSpeed(Math.max(.5f,Math.min(3f,x)));}catch(Exception ignored){}}).setNegativeButton("取消",null).show();}
    private void skipDialog(){LinearLayout form=column(0);form.setPadding(dp(24),0,dp(24),0);form.addView(label("片头跳过秒数（每集开始时跳过）",14,INK,true));EditText intro=new EditText(this);intro.setInputType(android.text.InputType.TYPE_CLASS_NUMBER);intro.setText(String.valueOf(service.introSkip()/1000));form.addView(intro);form.addView(label("片尾跳过秒数（剩余这些秒时播放下一集）",14,INK,true));EditText outro=new EditText(this);outro.setInputType(android.text.InputType.TYPE_CLASS_NUMBER);outro.setText(String.valueOf(service.outroSkip()/1000));form.addView(outro);form.addView(label("填 0 可关闭，最大 600 秒。设置按总合集分别保存；过短的音频不会强制跳过。",12,MUTED,false));new AlertDialog.Builder(this).setTitle("跳过片头和片尾").setView(form).setPositiveButton("保存",(d,w)->{long a=parseSkipSeconds(intro),b=parseSkipSeconds(outro);service.setSkipTimes(a*1000,b*1000);refreshPlayerFields();Toast.makeText(this,"已保存：片头 "+a+" 秒，片尾 "+b+" 秒",Toast.LENGTH_SHORT).show();}).setNegativeButton("取消",null).show();}
    private long parseSkipSeconds(EditText input){try{return Math.max(0,Math.min(600,Long.parseLong(input.getText().toString().trim())));}catch(Exception ignored){return 0;}}
    private void sleepDialog(){String[] x={"10 分钟","20 分钟","30 分钟","60 分钟","当前音频结束","关闭定时"};new AlertDialog.Builder(this).setTitle("睡眠定时").setItems(x,(d,w)->{if(w<4){long[]m={10,20,30,60};service.sleepIn(m[w]*60000);}else if(w==4)service.sleepAfterTrack();else service.sleepIn(0);refreshPlayerFields();}).show();}
    private void bookmarkDialog(){LibraryDb.Track t=service.current();if(t==null)return;EditText note=new EditText(this);note.setHint("备注（可选）");new AlertDialog.Builder(this).setTitle("在 "+format(service.position())+" 添加书签").setView(note).setPositiveButton("保存",(d,w)->{db.addBookmark(t.uri,service.position(),note.getText().toString());Toast.makeText(this,"书签已保存",Toast.LENGTH_SHORT).show();}).setNeutralButton("查看书签",(d,w)->showBookmarks(t)).setNegativeButton("取消",null).show();}
    private void showBookmarks(LibraryDb.Track t){List<String[]> b=db.bookmarks(t.uri);if(b.isEmpty()){Toast.makeText(this,"这段音频还没有书签",Toast.LENGTH_SHORT).show();return;}String[] items=new String[b.size()];for(int i=0;i<b.size();i++)items[i]=format(Long.parseLong(b.get(i)[1]))+(b.get(i)[2].isEmpty()?"":"  ·  "+b.get(i)[2]);new AlertDialog.Builder(this).setTitle("书签").setItems(items,(d,w)->service.seekTo(Long.parseLong(b.get(w)[1]))).show();}

    private void refreshMini(){if(!bound||service.current()==null){if(mini!=null)mini.setVisibility(View.GONE);return;}mini.setVisibility(View.VISIBLE);LibraryDb.Track t=service.current();miniTitle.setText(t.displayTitle());miniState.setText((service.isPlaying()?"播放中 · ":"已暂停 · ")+format(service.position())+" / "+format(service.duration()));View b=mini.findViewWithTag("miniPlay");if(b instanceof TextView)((TextView)b).setText(service.isPlaying()?"暂停":"播放");}
    private void pickFolder(){openFolderPicker(DocumentsContract.buildRootUri("com.android.externalstorage.documents","primary"));}
    private void openFolderPicker(Uri initialUri){if(scanning){Toast.makeText(this,"当前扫描尚未完成，请稍候再添加",Toast.LENGTH_SHORT).show();return;}if(pickingFolder)return;pickingFolder=true;Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT_TREE);i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION|Intent.FLAG_GRANT_PREFIX_URI_PERMISSION);i.putExtra(DocumentsContract.EXTRA_INITIAL_URI,initialUri);try{startActivityForResult(i,PICK_TREE);}catch(Exception e){pickingFolder=false;Toast.makeText(this,"无法打开系统文件夹选择器",Toast.LENGTH_LONG).show();}}
    private String coveringRoot(String authority,String selectedId){try{for(String[]root:db.roots()){if(root[0].startsWith("internal://"))continue;Uri rootUri=Uri.parse(root[0]);if(!Objects.equals(authority,rootUri.getAuthority()))continue;String rootId=DocumentsContract.getTreeDocumentId(rootUri);if(FolderIdentity.isSameOrDescendant(rootId,selectedId))return root[0];}}catch(Exception ignored){}return null;}
    @Override protected void onActivityResult(int req,int result,Intent data){super.onActivityResult(req,result,data);if(req!=PICK_TREE)return;pickingFolder=false;if(result!=RESULT_OK||data==null||scanning)return;Uri uri=data.getData();if(uri==null)return;String startId,name;try{startId=DocumentsContract.getTreeDocumentId(uri);name=folderDisplayName(uri);}catch(Exception e){Toast.makeText(this,"无法识别所选文件夹",Toast.LENGTH_LONG).show();return;}new FolderBrowserDialog(this,uri,startId,name,new FolderBrowserDialog.Listener(){public void onSelected(String documentId,String selectedName,String path){addSelectedFolder(uri,data,documentId,selectedName,path);}public void onCancelled(){showHome();}}).show();}
    private void addSelectedFolder(Uri pickerUri,Intent grantData,String documentId,String name,String path){if(scanning)return;String permissionUri=coveringRoot(pickerUri.getAuthority(),documentId);if(permissionUri==null){permissionUri=pickerUri.toString();try{if((grantData.getFlags()&Intent.FLAG_GRANT_READ_URI_PERMISSION)==0)throw new SecurityException("没有读取授权");getContentResolver().takePersistableUriPermission(pickerUri,Intent.FLAG_GRANT_READ_URI_PERMISSION);}catch(Exception e){Toast.makeText(this,"无法保存文件夹长期读取权限",Toast.LENGTH_LONG).show();return;}db.upsertRoot(permissionUri,folderDisplayName(pickerUri));}db.restoreExcludedDocument(documentId);if(db.coveringScanRoot(permissionUri,documentId)==null)db.upsertScanRoot(permissionUri,documentId,name,path);LibraryDb.Folder folder=new LibraryDb.Folder();folder.id=permissionUri+"#"+documentId;folder.rootUri=permissionUri;folder.parentId=null;folder.name=name;folder.path=path;beginScan();scanner.scanFolder(folder,scanCallback());}
    private String folderDisplayName(Uri uri){String id=DocumentsContract.getTreeDocumentId(uri);int p=id.lastIndexOf(':');String n=p>=0?id.substring(p+1):id;if(n.isEmpty())n="存储空间";int slash=n.lastIndexOf('/');return slash>=0?n.substring(slash+1):n;}
    private FolderScanner.Callback scanCallback(){return new FolderScanner.Callback(){public void onProgress(String t){}public void onDone(int f,int t){scanning=false;if(isFinishing()||isDestroyed())return;Toast.makeText(MainActivity.this,"扫描完成："+t+" 个音频，"+f+" 个文件夹",Toast.LENGTH_LONG).show();showHome();}public void onError(String m){scanning=false;if(isFinishing()||isDestroyed())return;Toast.makeText(MainActivity.this,"扫描失败："+m,Toast.LENGTH_LONG).show();showHome();}};}
    private void beginScan(){scanning=true;if(!isFinishing())showHome();Toast.makeText(this,"开始扫描，请稍候",Toast.LENGTH_SHORT).show();}
    private void rescan(){if(scanning){Toast.makeText(this,"当前扫描尚未完成",Toast.LENGTH_SHORT).show();return;}if(db.scanRoots().isEmpty()){pickFolder();return;}beginScan();scanner.scanAll(scanCallback());}

    private LinearLayout column(int gap){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);if(gap>0)l.setShowDividers(LinearLayout.SHOW_DIVIDER_MIDDLE);return l;}
    private LinearLayout card(){LinearLayout c=column(0);c.setPadding(dp(16),dp(15),dp(16),dp(15));c.setBackground(round(Color.WHITE,16));LinearLayout.LayoutParams p=lp(-1,-2);p.setMargins(0,dp(7),0,dp(7));c.setLayoutParams(p);return c;}
    private TextView label(String s,int size,int color,boolean bold){TextView v=new TextView(this);v.setText(s);v.setTextSize(size);v.setTextColor(color);v.setTypeface(Typeface.create("sans",bold?Typeface.BOLD:Typeface.NORMAL));v.setLineSpacing(0,1.12f);return v;}
    private TextView sectionTitle(String s){TextView v=label(s,18,INK,true);v.setPadding(0,dp(16),0,dp(5));return v;}
    private Button button(String s){Button b=new Button(this);b.setText(s);b.setTextSize(13);b.setTextColor(INK);b.setAllCaps(false);b.setGravity(Gravity.CENTER);b.setBackgroundColor(Color.TRANSPARENT);b.setMinHeight(0);b.setMinimumHeight(0);b.setPadding(dp(10),0,dp(10),0);return b;}
    private void stylePrimary(Button b){b.setTextColor(Color.WHITE);b.setBackground(round(GREEN,22));b.setPadding(dp(16),0,dp(16),0);}
    private View infoCard(String title,String body){LinearLayout c=card();c.addView(label(title,17,INK,true));c.addView(label(body,13,MUTED,false));return c;}
    private GradientDrawable round(int color,int radius){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(dp(radius));return g;}
    private LinearLayout.LayoutParams lp(int w,int h){return new LinearLayout.LayoutParams(w,h);}private int dp(int x){return (int)(x*getResources().getDisplayMetrics().density+.5f);}private String trimSpeed(float x){return x==(int)x?String.format(Locale.US,"%.1f",x):String.valueOf(x);}private static String format(long ms){long sec=Math.max(0,ms/1000),h=sec/3600,m=(sec%3600)/60,s=sec%60;return h>0?String.format(Locale.CHINA,"%d:%02d:%02d",h,m,s):String.format(Locale.CHINA,"%d:%02d",m,s);}
}
