package com.matianju.fm;

import android.Manifest;
import android.annotation.SuppressLint;
import android.app.*;
import android.content.*;
import android.content.pm.PackageManager;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.os.*;
import android.provider.DocumentsContract;
import android.text.TextUtils;
import android.view.*;
import android.view.inputmethod.EditorInfo;
import android.widget.*;
import java.text.*;
import java.util.*;
import java.util.regex.*;

@SuppressLint("SetTextI18n")
public final class MainActivity extends Activity {
    private static final int PICK_TREE=40;
    private final int INK=Color.rgb(17,29,39),PAPER=Color.rgb(246,243,236),GREEN=Color.rgb(23,107,91),GREEN_DARK=Color.rgb(0,81,68),GREEN_SOFT=Color.rgb(228,239,235),BLUE_SOFT=Color.rgb(237,244,255),AMBER=Color.rgb(228,154,66),MUTED=Color.rgb(105,113,118),OUTLINE=Color.rgb(221,226,223),MINI_BG=Color.rgb(30,41,59);
    private LibraryDb db; private FolderScanner scanner; private PlayerService service; private boolean bound=false,scanning=false,pickingFolder=false,returnToPlayerFromDirectory=false; private FrameLayout page; private LinearLayout mini; private TextView miniTitle,miniState; private ProgressBar miniProgress; private String openFolder=null; private final Handler ui=new Handler(Looper.getMainLooper());
    private final Runnable refresh=new Runnable(){public void run(){refreshMini();if(page!=null&&"player".equals(page.getTag()))refreshPlayerFields();ui.postDelayed(this,500);}};
    private TextView playerTitle,playerSubtitle,playerEpisode,elapsed,total; private SeekBar seek; private Button playButton,speedButton,sleepButton,skipButton;
    private final ServiceConnection connection=new ServiceConnection(){public void onServiceConnected(ComponentName n,android.os.IBinder b){service=((PlayerService.LocalBinder)b).service();bound=true;refreshMini();}public void onServiceDisconnected(ComponentName n){bound=false;service=null;}};

    @Override public void onCreate(Bundle state){super.onCreate(state);db=LibraryDb.get(this);SampleContent.ensure(this);db.scanRoots();scanner=new FolderScanner(this);getWindow().setStatusBarColor(PAPER);getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR);buildShell();showHome();bindService(new Intent(this,PlayerService.class),connection,BIND_AUTO_CREATE);if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},5);ui.post(refresh);}
    @Override protected void onDestroy(){ui.removeCallbacks(refresh);if(bound)unbindService(connection);super.onDestroy();}
    @Override public void onBackPressed(){if(returnToPlayerFromDirectory&&"folder".equals(page.getTag())){returnToPlayerFromDirectory=false;showPlayer();}else if("player".equals(page.getTag())){if(openFolder!=null)showFolder(openFolder);else showHome();}else if(openFolder!=null){LibraryDb.Folder f=db.folder(openFolder);if(f!=null&&f.parentId!=null&&db.folder(f.parentId)!=null)showFolder(f.parentId);else showHome();}else super.onBackPressed();}

    private void buildShell(){
        LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(PAPER);
        root.setOnApplyWindowInsetsListener((v,insets)->{v.setPadding(0,insets.getSystemWindowInsetTop(),0,0);return insets;});
        page=new FrameLayout(this);root.addView(page,new LinearLayout.LayoutParams(-1,0,1));
        mini=new LinearLayout(this);mini.setOrientation(LinearLayout.VERTICAL);mini.setBackgroundColor(MINI_BG);mini.setVisibility(View.GONE);
        miniProgress=styledProgress(AMBER,Color.rgb(68,81,99));miniProgress.setMax(1000);mini.addView(miniProgress,new LinearLayout.LayoutParams(-1,dp(3)));
        LinearLayout content=column(0);content.setPadding(dp(14),dp(7),dp(14),dp(8));
        LinearLayout meta=new LinearLayout(this);meta.setGravity(Gravity.CENTER_VERTICAL);
        TextView audioIcon=label("♫",16,Color.WHITE,true);audioIcon.setGravity(Gravity.CENTER);audioIcon.setBackground(round(Color.rgb(52,66,84),8));meta.addView(audioIcon,new LinearLayout.LayoutParams(dp(36),dp(36)));
        LinearLayout miniMeta=column(0);miniMeta.setPadding(dp(10),0,dp(8),0);miniTitle=label("",14,Color.WHITE,true);miniTitle.setSingleLine(true);miniTitle.setEllipsize(TextUtils.TruncateAt.END);miniState=label("",11,Color.rgb(205,215,226),false);miniState.setSingleLine(true);miniMeta.addView(miniTitle);miniMeta.addView(miniState);meta.addView(miniMeta,new LinearLayout.LayoutParams(0,dp(38),1));content.addView(meta,new LinearLayout.LayoutParams(-1,dp(40)));
        LinearLayout controls=new LinearLayout(this);controls.setGravity(Gravity.CENTER);
        TextView previous=miniControl("上一首",false);previous.setOnClickListener(v->{if(bound)service.previous();});
        TextView back=miniControl("−15 秒",false);back.setOnClickListener(v->{if(bound)service.skip(-15000);});
        TextView toggle=miniControl("播放",true);toggle.setTag("miniPlay");toggle.setOnClickListener(v->{if(bound)service.toggle();});
        TextView forward=miniControl("+15 秒",false);forward.setOnClickListener(v->{if(bound)service.skip(15000);});
        TextView next=miniControl("下一首",false);next.setOnClickListener(v->{if(bound)service.next();});
        controls.addView(previous);controls.addView(back);controls.addView(toggle);controls.addView(forward);controls.addView(next);content.addView(controls,new LinearLayout.LayoutParams(-1,dp(44)));
        meta.setOnClickListener(v->showPlayer());mini.addView(content);root.addView(mini);setContentView(root);root.requestApplyInsets();
    }
    private TextView miniControl(String text,boolean primary){TextView v=label(text,13,primary?INK:Color.WHITE,true);v.setGravity(Gravity.CENTER);v.setBackground(primary?round(AMBER,22):round(Color.TRANSPARENT,18));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(40),1);p.setMargins(dp(2),dp(2),dp(2),dp(2));v.setLayoutParams(p);return v;}
    private void setPage(View v,String tag){page.removeAllViews();page.setTag(tag);page.addView(v,new FrameLayout.LayoutParams(-1,-1));refreshMini();}

    private void showHome(){
        openFolder=null;ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);LinearLayout body=column(0);body.setPadding(dp(20),dp(14),dp(20),dp(32));
        LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);
        LinearLayout brand=column(0);brand.addView(label("马天驹 FM",27,GREEN_DARK,true));brand.addView(label("把文件夹听完",13,MUTED,false));head.addView(brand,new LinearLayout.LayoutParams(0,-2,1));
        Button add=button(scanning?"扫描中":"＋  文件夹");add.setTextColor(GREEN_DARK);add.setTextSize(13);add.setBackground(roundStroke(Color.WHITE,16,OUTLINE,1));add.setEnabled(!scanning&&!pickingFolder);add.setAlpha(add.isEnabled()?1f:.55f);add.setOnClickListener(v->pickFolder());head.addView(add,new LinearLayout.LayoutParams(dp(96),dp(48)));body.addView(head);
        SearchView search=searchBox("搜索文件夹或音频");LinearLayout.LayoutParams sp=lp(-1,dp(56));sp.setMargins(0,dp(24),0,dp(18));body.addView(search,sp);search.setOnQueryTextListener(new SearchView.OnQueryTextListener(){public boolean onQueryTextSubmit(String q){showSearch(q);return true;}public boolean onQueryTextChange(String q){return false;}});
        if(scanning){LinearLayout scanningCard=infoCard("正在扫描本地文件","扫描会递归读取全部子文件夹，完成前仍可继续使用播放器。");scanningCard.setBackground(roundStroke(BLUE_SOFT,16,OUTLINE,1));body.addView(scanningCard);}
        LibraryDb.Track last=db.lastPlayed();body.addView(sectionTitle("继续播放"));if(last==null)body.addView(infoCard("还没有播放记录","选择一段音频后，这里会自动记住文件和播放位置。"));else body.addView(continueCard(last));
        LinearLayout sectionHead=new LinearLayout(this);sectionHead.setGravity(Gravity.CENTER_VERTICAL);sectionHead.addView(sectionTitle("我的文件夹"),new LinearLayout.LayoutParams(0,-2,1));
        if(!db.excludedFolders().isEmpty()){Button excluded=sectionAction("已移出");excluded.setOnClickListener(v->showExcludedFolders());sectionHead.addView(excluded);}
        Button scan=sectionAction("重新扫描");scan.setOnClickListener(v->rescan());sectionHead.addView(scan);body.addView(sectionHead);
        List<LibraryDb.Folder> folders=db.topLevelFolders();if(folders.isEmpty())body.addView(emptyLibrary());else for(LibraryDb.Folder f:folders)body.addView(folderCard(f));
        body.addView(privacyCard());scroll.addView(body);setPage(scroll,"home");
    }
    private View emptyLibrary(){LinearLayout c=card();c.setGravity(Gravity.CENTER);c.setPadding(dp(24),dp(30),dp(24),dp(26));TextView icon=label("♫",34,GREEN,true);icon.setGravity(Gravity.CENTER);icon.setBackground(round(GREEN_SOFT,24));c.addView(icon,new LinearLayout.LayoutParams(dp(64),dp(64)));TextView t=label("还没有本地音频",20,INK,true);t.setGravity(Gravity.CENTER);t.setPadding(0,dp(18),0,0);c.addView(t);TextView d=label("选择包含课程、录音、有声书或播客的文件夹。音频只在本机读取，不会上传。",14,MUTED,false);d.setGravity(Gravity.CENTER);d.setPadding(dp(8),dp(8),dp(8),dp(20));c.addView(d);Button b=button("选择文件夹");stylePrimary(b);b.setOnClickListener(v->pickFolder());c.addView(b,new LinearLayout.LayoutParams(-1,dp(50)));return c;}
    private View privacyCard(){TextView v=label("▣  全部本地处理，不上传音频文件",12,MUTED,true);v.setGravity(Gravity.CENTER);v.setPadding(dp(14),dp(24),dp(14),dp(12));return v;}
    private View continueCard(LibraryDb.Track t){
        String profile=db.playbackProfileId(t.folderId);List<LibraryDb.Track>queue=db.tracksInSubtree(profile,null,false);LibraryDb.Folder f=db.folder(profile);
        LinearLayout c=card();c.setOnClickListener(v->openTrack(t,queue));LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);
        TextView art=label(episodeNumber(t.name),18,Color.rgb(156,233,212),true);art.setGravity(Gravity.CENTER);art.setBackground(round(GREEN,12));row.addView(art,new LinearLayout.LayoutParams(dp(72),dp(72)));
        LinearLayout text=column(0);text.setPadding(dp(14),0,dp(10),0);TextView folder=label(f==null?"本地音频":f.name,13,MUTED,true);text.addView(folder);TextView title=label(t.displayTitle(),17,INK,true);title.setSingleLine(true);title.setEllipsize(TextUtils.TruncateAt.END);text.addView(title);text.addView(label("听到 "+format(t.position)+" · 共 "+format(t.duration),13,MUTED,false));row.addView(text,new LinearLayout.LayoutParams(0,-2,1));
        TextView play=label("▶",23,Color.WHITE,true);play.setGravity(Gravity.CENTER);play.setBackground(round(AMBER,30));play.setOnClickListener(v->openTrack(t,queue));row.addView(play,new LinearLayout.LayoutParams(dp(58),dp(58)));c.addView(row);
        ProgressBar p=styledProgress(GREEN,Color.rgb(210,226,221));p.setMax(1000);p.setProgress(t.duration>0?(int)(t.position*1000/t.duration):0);LinearLayout.LayoutParams pp=lp(-1,dp(7));pp.setMargins(0,dp(16),0,0);c.addView(p,pp);return c;
    }
    private View folderCard(LibraryDb.Folder f){
        LinearLayout c=card();c.setTag("folder:"+f.id);c.setOnClickListener(v->showFolder(f.id));LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);
        TextView icon=label("▰",22,GREEN_DARK,true);icon.setGravity(Gravity.CENTER);icon.setBackground(round(BLUE_SOFT,12));row.addView(icon,new LinearLayout.LayoutParams(dp(52),dp(52)));
        LinearLayout texts=column(0);texts.setPadding(dp(14),0,0,0);TextView name=label(f.name,18,INK,true);name.setSingleLine(true);name.setEllipsize(TextUtils.TruncateAt.END);texts.addView(name);String path=f.path.equals(f.name)?"本地文件夹":f.path;texts.addView(label(path,13,MUTED,false));row.addView(texts,new LinearLayout.LayoutParams(0,-2,1));
        TextView more=label("⋮",26,MUTED,true);more.setGravity(Gravity.CENTER);more.setOnClickListener(v->folderMenu(f));row.addView(more,new LinearLayout.LayoutParams(dp(44),dp(48)));c.addView(row);
        LinearLayout detail=new LinearLayout(this);detail.setPadding(0,dp(13),0,dp(6));detail.addView(label(f.count+" 个音频 · "+format(f.totalDuration),12,MUTED,true),new LinearLayout.LayoutParams(0,-2,1));int percent=f.count==0?0:(int)Math.round(f.completed*100d/f.count);detail.addView(label(percent+"%",12,MUTED,true));c.addView(detail);
        ProgressBar p=styledProgress(GREEN,Color.rgb(210,226,221));p.setMax(Math.max(1,f.count));p.setProgress(f.completed);c.addView(p,new LinearLayout.LayoutParams(-1,dp(6)));return c;
    }

    private void showFolder(String id){showFolder(id,null);}
    private void showFolder(String id,String exactTrackUri){
        LibraryDb.Folder f=db.folder(id);if(f==null)return;openFolder=id;LinearLayout root=column(0);root.setPadding(dp(16),dp(8),dp(16),0);
        LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);
        Button back=button("←");back.setTextColor(GREEN_DARK);back.setTextSize(26);back.setPadding(0,0,0,0);back.setOnClickListener(v->{if(returnToPlayerFromDirectory){returnToPlayerFromDirectory=false;showPlayer();}else if(f.parentId!=null&&db.folder(f.parentId)!=null)showFolder(f.parentId);else showHome();});head.addView(back,new LinearLayout.LayoutParams(dp(48),dp(52)));
        LinearLayout title=column(0);TextView titleText=label(f.name,24,INK,true);titleText.setGravity(Gravity.CENTER);titleText.setSingleLine(true);titleText.setEllipsize(TextUtils.TruncateAt.END);title.addView(titleText);TextView meta=label(f.count+" 个音频 · "+format(f.totalDuration),12,MUTED,true);meta.setGravity(Gravity.CENTER);title.addView(meta);head.addView(title,new LinearLayout.LayoutParams(0,-2,1));
        Button menu=button("⋮");menu.setTextColor(GREEN_DARK);menu.setTextSize(26);menu.setOnClickListener(v->folderMenu(f));head.addView(menu,new LinearLayout.LayoutParams(dp(48),dp(52)));root.addView(head);
        SearchView search=searchBox("搜索这个合集及全部子文件夹");LinearLayout.LayoutParams slp=lp(-1,dp(54));slp.setMargins(0,dp(16),0,dp(8));root.addView(search,slp);
        List<LibraryDb.Track>allTracks=db.tracksInSubtree(id,null,false);LinearLayout actionRow=new LinearLayout(this);actionRow.setGravity(Gravity.CENTER_VERTICAL);TextView hierarchy=label("包含当前文件夹和全部子文件夹",12,MUTED,false);actionRow.addView(hierarchy,new LinearLayout.LayoutParams(0,-2,1));Button play=button("▶  全部播放");stylePrimary(play);actionRow.addView(play,new LinearLayout.LayoutParams(dp(112),dp(40)));root.addView(actionRow);
        ScrollView scroll=new ScrollView(this);LinearLayout list=column(0);renderFolderContents(list,id,"");scroll.addView(list);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));play.setOnClickListener(v->{if(!allTracks.isEmpty())startTrack(allTracks,0,false);});search.setOnQueryTextListener(new SearchView.OnQueryTextListener(){public boolean onQueryTextSubmit(String q){return true;}public boolean onQueryTextChange(String q){renderFolderContents(list,id,q);return true;}});setPage(root,"folder");if(exactTrackUri==null)scrollToLastPlayed(scroll,list,id);else scrollToTrack(scroll,list,exactTrackUri);
    }
    private void scrollToTrack(ScrollView scroll,LinearLayout list,String trackUri){String anchor="track:"+trackUri;scroll.post(()->{View target=list.findViewWithTag(anchor);if(target!=null)scroll.scrollTo(0,Math.max(0,target.getTop()-Math.max(dp(10),scroll.getHeight()/3)));});}
    private void scrollToLastPlayed(ScrollView scroll,LinearLayout list,String folderId){LibraryDb.Track recent=db.lastPlayedInSubtree(folderId);if(recent==null)return;String anchor;if(folderId.equals(recent.folderId))anchor="track:"+recent.uri;else{String child=db.directChildToward(folderId,recent.folderId);if(child==null)return;anchor="folder:"+child;}scroll.post(()->{View target=list.findViewWithTag(anchor);if(target!=null)scroll.scrollTo(0,Math.max(0,target.getTop()-dp(10)));});}
    private void renderFolderContents(LinearLayout list,String folderId,String query){
        list.removeAllViews();String q=query==null?"":query.trim();
        if(q.isEmpty()){
            List<LibraryDb.Folder>children=db.childFolders(folderId);if(!children.isEmpty()){list.addView(sectionTitle("子文件夹（"+children.size()+"）"));LinearLayout grid=column(0);for(int i=0;i<children.size();i+=2){LinearLayout line=new LinearLayout(this);line.setGravity(Gravity.TOP);line.addView(compactFolderCard(children.get(i)));if(i+1<children.size())line.addView(compactFolderCard(children.get(i+1)));else{Space blank=new Space(this);LinearLayout.LayoutParams blankParams=new LinearLayout.LayoutParams(0,dp(78),1);blankParams.setMargins(dp(3),dp(3),dp(3),dp(3));line.addView(blank,blankParams);}grid.addView(line);}list.addView(grid);}
            List<LibraryDb.Track>direct=db.tracks(folderId,null,false);if(!direct.isEmpty()){LinearLayout heading=new LinearLayout(this);heading.setGravity(Gravity.CENTER_VERTICAL);heading.addView(sectionTitle("当前文件夹音频（"+direct.size()+"）"),new LinearLayout.LayoutParams(0,-2,1));TextView sort=label("≡  自然排序",12,GREEN_DARK,true);sort.setPadding(dp(8),dp(16),0,dp(5));heading.addView(sort);list.addView(heading);List<LibraryDb.Track>queue=db.tracksInSubtree(folderId,null,false);for(int i=0;i<direct.size();i++)list.addView(trackRow(direct.get(i),queue,indexOf(queue,direct.get(i).uri),true));}
            if(children.isEmpty()&&direct.isEmpty())list.addView(infoCard("没有找到音频","这个文件夹及其子文件夹中没有可识别的音频文件。"));return;
        }
        List<LibraryDb.Track>matches=db.tracksInSubtree(folderId,q,false);list.addView(sectionTitle("搜索结果（"+matches.size()+"）"));for(int i=0;i<matches.size();i++)list.addView(trackRow(matches.get(i),matches,i,true));if(matches.isEmpty())list.addView(infoCard("没有找到","请尝试其他文件名或音频标签。"));
    }
    private void folderMenu(LibraryDb.Folder f){String[]items={"移出资料库","重新扫描此目录","清除全部播放记录"};new AlertDialog.Builder(this).setTitle(f.name).setItems(items,(d,w)->{if(w==0)confirmRemoveFolder(f);else if(w==1)rescanFolder(f);else confirmClearFolderProgress(f);}).setNegativeButton("取消",null).show();}
    private void confirmRemoveFolder(LibraryDb.Folder f){boolean sample=SampleContent.isSample(f),root=!sample&&db.isScanRoot(f.id);String message=sample?"将删除 App 本地示例目录中的试听音频，今后启动时不会自动恢复。":root?"将从马天驹 FM 移除这个已添加目录。只有没有其他目录共用授权时，才会同时释放读取权限。手机里的音频文件不会被删除。":"将从马天驹 FM 移除此合集及其子目录。它会进入排除名单，重新扫描也不会自动出现。手机里的音频文件不会被删除。";new AlertDialog.Builder(this).setTitle("移出“"+f.name+"”？").setMessage(message).setPositiveButton("移出资料库",(d,w)->{stopIfPlayingIn(f);if(sample)SampleContent.remove(this);else if(root){boolean release=db.removeScanRoot(f.id);if(release)try{getContentResolver().releasePersistableUriPermission(Uri.parse(f.rootUri),Intent.FLAG_GRANT_READ_URI_PERMISSION);}catch(Exception ignored){}}else db.excludeFolder(f);openFolder=null;Toast.makeText(this,sample?"内置示例已删除":"已移出资料库，本地文件未删除",Toast.LENGTH_LONG).show();showHome();}).setNegativeButton("取消",null).show();}
    private void confirmClearFolderProgress(LibraryDb.Folder f){new AlertDialog.Builder(this).setTitle("清除全部播放记录？").setMessage("将清除“"+f.name+"”及其子目录中所有音频的播放位置、已听状态和最近播放时间。收藏、书签和本地文件不受影响。").setPositiveButton("确认清除",(d,w)->{stopIfPlayingIn(f);db.clearFolderProgress(f.id);Toast.makeText(this,"播放记录已清除",Toast.LENGTH_SHORT).show();showFolder(f.id);}).setNegativeButton("取消",null).show();}
    private void stopIfPlayingIn(LibraryDb.Folder f){if(bound&&service.current()!=null&&db.isInSubtree(f.id,service.current().folderId))service.stopAndClear();}
    private void rescanFolder(LibraryDb.Folder f){if(SampleContent.isSample(f)){SampleContent.ensure(this);Toast.makeText(this,"内置示例无需扫描",Toast.LENGTH_SHORT).show();showFolder(f.id);return;}if(scanning){Toast.makeText(this,"当前扫描尚未完成",Toast.LENGTH_SHORT).show();return;}beginScan();scanner.scanFolder(f,scanCallback());}
    private void showExcludedFolders(){List<String[]>items=db.excludedFolders();if(items.isEmpty()){Toast.makeText(this,"没有已移出的目录",Toast.LENGTH_SHORT).show();return;}String[]labels=new String[items.size()];for(int i=0;i<items.size();i++)labels[i]=items.get(i)[2]+"\n"+items.get(i)[3];new AlertDialog.Builder(this).setTitle("已移出目录").setItems(labels,(d,w)->{String[]x=items.get(w);new AlertDialog.Builder(this).setTitle("恢复“"+x[2]+"”？").setMessage("恢复后将重新扫描它所属的已添加目录。").setPositiveButton("恢复",(d2,w2)->{db.restoreExcluded(x[0]);if(db.scanRoots().isEmpty()){Toast.makeText(this,"原授权文件夹已不存在，请重新添加",Toast.LENGTH_LONG).show();showHome();}else rescan();}).setNegativeButton("取消",null).show();}).setNegativeButton("关闭",null).show();}
    private View trackRow(LibraryDb.Track t,List<LibraryDb.Track> queue,int index,boolean menu){
        boolean current=bound&&service.current()!=null&&t.uri.equals(service.current().uri);LinearLayout row=new LinearLayout(this);row.setTag("track:"+t.uri);row.setGravity(Gravity.CENTER_VERTICAL);row.setMinimumHeight(dp(76));row.setPadding(dp(12),dp(10),dp(6),dp(10));row.setBackground(roundStroke(current?GREEN_SOFT:Color.argb(190,255,255,255),12,current?Color.rgb(190,215,207):OUTLINE,1));
        TextView status=label(current?"▥":t.completed?"✓":t.position>0?"▶":"",15,current?Color.WHITE:t.completed?MUTED:GREEN,true);status.setGravity(Gravity.CENTER);status.setBackground(current?round(GREEN,22):t.completed?round(BLUE_SOFT,22):roundStroke(Color.TRANSPARENT,22,AMBER,2));row.addView(status,new LinearLayout.LayoutParams(dp(42),dp(42)));
        LinearLayout text=column(0);text.setPadding(dp(14),0,dp(4),0);TextView title=label(t.displayTitle(),16,current?GREEN_DARK:t.completed?MUTED:INK,true);title.setMaxLines(2);title.setEllipsize(TextUtils.TruncateAt.END);if(t.completed)title.setPaintFlags(title.getPaintFlags()|android.graphics.Paint.STRIKE_THRU_TEXT_FLAG);text.addView(title);
        String detail=format(t.duration);if(current)detail="正在播放  ·  "+format(service.position())+" / "+format(service.duration());else if(t.position>0&&!t.completed)detail="听到 "+format(t.position)+"  ·  "+detail;else if(t.completed)detail="已听完  ·  "+detail;else detail="未播放  ·  "+detail;TextView detailView=label(detail,12,current?GREEN_DARK:MUTED,current);text.addView(detailView);row.addView(text,new LinearLayout.LayoutParams(0,-2,1));
        TextView more=label(t.favorite?"★":"⋮",23,t.favorite?AMBER:MUTED,true);more.setGravity(Gravity.CENTER);more.setVisibility(menu?View.VISIBLE:View.INVISIBLE);row.addView(more,new LinearLayout.LayoutParams(dp(42),dp(46)));row.setOnClickListener(v->openTrack(t,queue));more.setOnClickListener(v->trackMenu(t));LinearLayout.LayoutParams rp=lp(-1,-2);rp.setMargins(0,0,0,dp(6));row.setLayoutParams(rp);return row;
    }
    private void trackMenu(LibraryDb.Track t){String[] items={t.favorite?"取消收藏":"收藏",t.completed?"标记为未听":"标记为已听","清除播放进度"};new AlertDialog.Builder(this).setTitle(t.displayTitle()).setItems(items,(d,w)->{if(w==0)db.toggleFavorite(t.uri);else if(w==1)db.setCompleted(t.uri,!t.completed);else db.saveProgress(t.uri,0,t.duration,false);if(openFolder!=null)showFolder(openFolder);else showHome();}).show();}

    private void showSearch(String q){LinearLayout root=column(0);root.setPadding(dp(18),dp(8),dp(18),0);LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);Button back=button("←");back.setTextSize(25);back.setTextColor(GREEN_DARK);back.setOnClickListener(v->showHome());head.addView(back,new LinearLayout.LayoutParams(dp(48),dp(52)));LinearLayout title=column(0);title.addView(label("搜索结果",23,INK,true));title.addView(label("“"+q+"”",12,MUTED,false));head.addView(title);root.addView(head);ScrollView s=new ScrollView(this);LinearLayout list=column(0);List<LibraryDb.Folder> folders=db.folders(q);if(!folders.isEmpty()){list.addView(sectionTitle("文件夹（"+folders.size()+"）"));for(LibraryDb.Folder f:folders)list.addView(folderCard(f));}List<LibraryDb.Track> tracks=db.tracks(null,q,false);if(!tracks.isEmpty()){list.addView(sectionTitle("音频（"+tracks.size()+"）"));for(int i=0;i<tracks.size();i++)list.addView(trackRow(tracks.get(i),db.tracks(tracks.get(i).folderId,null,false),0,true));}if(list.getChildCount()==0)list.addView(infoCard("没有找到","请尝试文件名、文件夹名或音频标签。"));s.addView(list);root.addView(s,new LinearLayout.LayoutParams(-1,0,1));setPage(root,"search");}

    private void openTrack(LibraryDb.Track t,List<LibraryDb.Track> queue){if(t.position>0&&!t.completed){new AlertDialog.Builder(this).setTitle("继续上次播放？").setMessage(t.displayTitle()+"\n上次听到 "+format(t.position)).setPositiveButton("继续播放",(d,w)->startTrack(queue,indexOf(queue,t.uri),false)).setNegativeButton("从头播放",(d,w)->startTrack(queue,indexOf(queue,t.uri),true)).show();}else startTrack(queue,indexOf(queue,t.uri),true);}
    private int indexOf(List<LibraryDb.Track> q,String uri){for(int i=0;i<q.size();i++)if(q.get(i).uri.equals(uri))return i;return 0;}
    private void startTrack(List<LibraryDb.Track> queue,int at,boolean fromStart){if(!bound){Toast.makeText(this,"播放服务正在启动，请再试一次",Toast.LENGTH_SHORT).show();return;}if(queue.isEmpty())return;returnToPlayerFromDirectory=false;if(fromStart){LibraryDb.Track t=queue.get(at);db.saveProgress(t.uri,0,t.duration,false);t.position=0;}startService(new Intent(this,PlayerService.class));service.loadQueue(queue,at,true);String profile=db.playbackProfileId(queue.get(at).folderId);float saved=Float.parseFloat(db.setting("speed_"+profile,"1.0"));service.setSpeed(saved);showPlayer();}

    private void showPlayer(){
        if(!bound||service.current()==null){Toast.makeText(this,"还没有正在播放的音频",Toast.LENGTH_SHORT).show();return;}
        LinearLayout screen=column(0);LinearLayout root=screen;root.setGravity(Gravity.CENTER_HORIZONTAL);root.setPadding(dp(20),dp(2),dp(20),dp(4));
        LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER);LinearLayout heading=column(0);TextView headingTitle=label("正在播放",15,INK,true);headingTitle.setGravity(Gravity.CENTER);TextView headingSub=label("本地有声内容",11,MUTED,false);headingSub.setGravity(Gravity.CENTER);heading.addView(headingTitle);heading.addView(headingSub);top.addView(heading,new LinearLayout.LayoutParams(-1,-2));root.addView(top,new LinearLayout.LayoutParams(-1,dp(40)));
        Space topFiller=new Space(this);root.addView(topFiller,new LinearLayout.LayoutParams(-1,0,.35f));
        float density=getResources().getDisplayMetrics().density;int availableDp=page.getHeight()>0?Math.round(page.getHeight()/density):Math.round(getResources().getDisplayMetrics().heightPixels/density)-120;int coverDp=Math.max(180,Math.min(260,availableDp-340));int coverSize=Math.min(dp(coverDp),getResources().getDisplayMetrics().widthPixels-dp(56));LinearLayout cover=column(0);cover.setGravity(Gravity.CENTER);cover.setPadding(dp(16),dp(14),dp(16),dp(14));cover.setBackground(playerCoverBackground());playerEpisode=label("当前集",27,Color.rgb(156,233,212),true);playerEpisode.setGravity(Gravity.CENTER);cover.addView(playerEpisode);TextView coverBrand=label("马天驹 FM  ·  本地听书",13,Color.rgb(137,213,193),false);coverBrand.setGravity(Gravity.CENTER);coverBrand.setPadding(0,dp(8),0,0);cover.addView(coverBrand);LinearLayout.LayoutParams coverParams=lp(coverSize,coverSize);coverParams.setMargins(0,dp(4),0,dp(6));root.addView(cover,coverParams);
        Space coverFiller=new Space(this);root.addView(coverFiller,new LinearLayout.LayoutParams(-1,0,.75f));
        playerTitle=label("",19,INK,true);playerTitle.setGravity(Gravity.START);playerTitle.setMaxLines(2);playerTitle.setEllipsize(TextUtils.TruncateAt.END);root.addView(playerTitle,lp(-1,-2));playerSubtitle=label("",12,MUTED,false);playerSubtitle.setGravity(Gravity.START);playerSubtitle.setPadding(0,dp(3),0,0);root.addView(playerSubtitle,lp(-1,-2));Space metaFiller=new Space(this);root.addView(metaFiller,new LinearLayout.LayoutParams(-1,0,.45f));
        LinearLayout progress=column(0);seek=new SeekBar(this);seek.setMax(1000);seek.setThumb(seekThumb());seek.setThumbOffset(dp(11));seek.setProgressTintList(android.content.res.ColorStateList.valueOf(GREEN));seek.setProgressBackgroundTintList(android.content.res.ColorStateList.valueOf(Color.rgb(210,226,221)));seek.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onProgressChanged(SeekBar s,int p,boolean user){}public void onStartTrackingTouch(SeekBar s){}public void onStopTrackingTouch(SeekBar s){if(bound)service.seekTo(service.duration()*s.getProgress()/1000);}});progress.addView(seek,lp(-1,dp(36)));LinearLayout times=new LinearLayout(this);elapsed=label("0:00",12,MUTED,true);total=label("0:00",12,MUTED,false);times.addView(elapsed,new LinearLayout.LayoutParams(0,-2,1));times.addView(total);progress.addView(times);LinearLayout.LayoutParams progressParams=lp(-1,dp(58));progressParams.setMargins(0,dp(10),0,dp(4));root.addView(progress,progressParams);
        LinearLayout listeningTools=new LinearLayout(this);listeningTools.setGravity(Gravity.CENTER);listeningTools.setPadding(dp(4),dp(2),dp(4),dp(2));listeningTools.setBackground(round(BLUE_SOFT,18));Button minus=toolButton("↶\n15秒");minus.setOnClickListener(v->service.skip(-15000));speedButton=toolButton("1.0×\n倍速");speedButton.setOnClickListener(v->speedDialog());skipButton=toolButton("片头片尾\n0 / 0秒");skipButton.setOnClickListener(v->skipDialog());Button plus=toolButton("↷\n15秒");plus.setOnClickListener(v->service.skip(15000));listeningTools.addView(minus);listeningTools.addView(speedButton);listeningTools.addView(skipButton);listeningTools.addView(plus);LinearLayout.LayoutParams toolParams=lp(-1,dp(60));toolParams.setMargins(0,dp(2),0,0);root.addView(listeningTools,toolParams);
        Space controlsFiller=new Space(this);root.addView(controlsFiller,new LinearLayout.LayoutParams(-1,0,.7f));
        LinearLayout mainControls=new LinearLayout(this);mainControls.setGravity(Gravity.CENTER);Button directory=playerNavButton("≡♪","目录");directory.setOnClickListener(v->openCurrentDirectory());Button prev=playerNavButton("│◀","上一首");prev.setOnClickListener(v->service.previous());playButton=roundControl("Ⅱ\n暂停",true);playButton.setOnClickListener(v->service.toggle());Button next=playerNavButton("▶│","下一首");next.setOnClickListener(v->service.next());sleepButton=timerButton();sleepButton.setOnClickListener(v->sleepDialog());mainControls.addView(directory);mainControls.addView(prev);mainControls.addView(playButton);mainControls.addView(next);mainControls.addView(sleepButton);LinearLayout.LayoutParams mainParams=lp(-1,dp(82));mainParams.setMargins(0,dp(6),0,dp(2));root.addView(mainControls,mainParams);
        setPage(screen,"player");refreshPlayerFields();
    }
    private void openCurrentDirectory(){if(!bound||service.current()==null)return;LibraryDb.Track current=service.current();returnToPlayerFromDirectory=true;showFolder(current.folderId,current.uri);}
    private Button roundControl(String text,boolean main){Button b=button(text);b.setTextColor(main?Color.WHITE:INK);b.setTextSize(15);b.setBackground(round(main?AMBER:Color.TRANSPARENT,50));b.setAllCaps(false);b.setPadding(dp(5),0,dp(5),0);b.setMinWidth(0);b.setMinimumWidth(0);LinearLayout.LayoutParams p=lp(dp(80),dp(80));p.setMargins(dp(2),0,dp(2),0);b.setLayoutParams(p);return b;}
    private Button playerNavButton(String icon,String caption){Button b=button(icon+"\n"+caption);b.setTextSize(12);b.setTypeface(Typeface.create("sans",Typeface.NORMAL));b.setTextColor(INK);b.setGravity(Gravity.CENTER);b.setMinWidth(0);b.setMinimumWidth(0);b.setPadding(dp(2),0,dp(2),0);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(72),1);p.setMargins(dp(1),0,dp(1),0);b.setLayoutParams(p);return b;}
    private Button timerButton(){return playerNavButton("◴","定时");}
    private Button toolButton(String text){Button b=button(text);b.setTextSize(11);b.setTextColor(INK);b.setGravity(Gravity.CENTER);b.setBackground(round(Color.TRANSPARENT,12));b.setMinWidth(0);b.setMinimumWidth(0);b.setPadding(dp(2),0,dp(2),0);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(60),1);p.setMargins(dp(2),dp(1),dp(2),dp(1));b.setLayoutParams(p);return b;}
    private GradientDrawable seekThumb(){GradientDrawable g=new GradientDrawable();g.setShape(GradientDrawable.OVAL);g.setColor(GREEN);g.setSize(dp(22),dp(22));return g;}
    private GradientDrawable playerCoverBackground(){GradientDrawable g=new GradientDrawable(GradientDrawable.Orientation.TL_BR,new int[]{Color.rgb(19,118,97),Color.rgb(14,72,76)});g.setCornerRadius(dp(24));return g;}
    private void refreshPlayerFields(){if(!bound||service.current()==null||playerTitle==null)return;LibraryDb.Track t=db.track(service.current().uri);if(t==null)t=service.current();playerEpisode.setText(episodeLabel(t.name));playerTitle.setText(t.displayTitle());LibraryDb.Folder f=db.folder(t.folderId);playerSubtitle.setText((f==null?"本地音频":f.name)+" · 顺序播放");long pos=service.position(),dur=service.duration();elapsed.setText(format(pos));total.setText(format(dur));seek.setProgress(dur>0?(int)(pos*1000/dur):0);playButton.setText(service.isPlaying()?"Ⅱ\n暂停":"▶\n播放");speedButton.setText(trimSpeed(service.speed())+"×\n倍速");skipButton.setText("片头片尾\n"+(service.introSkip()/1000)+" / "+(service.outroSkip()/1000)+"秒");long rem=service.sleepRemaining();sleepButton.setText(rem>0?"◴\n"+((rem+59999)/60000)+"分":service.sleepAfterTrackEnabled()?"◴\n本集后":"◴\n定时");}
    private String episodeLabel(String name){Matcher m=Pattern.compile("(?<!\\d)(\\d{1,6})(?!\\d)").matcher(name==null?"":name);if(!m.find())return "当前集";try{return "第 "+Long.parseLong(m.group(1))+" 集";}catch(Exception ignored){return "第 "+m.group(1)+" 集";}}
    private void speedDialog(){String[] values={"0.5×","0.75×","1.0×","1.25×","1.5×","1.75×","2.0×","2.5×","3.0×","自定义"};new AlertDialog.Builder(this).setTitle("播放速度（按合集记忆）").setItems(values,(d,w)->{if(w<9)service.setSpeed(Float.parseFloat(values[w].replace("×","")));else customSpeed();refreshPlayerFields();}).show();}
    private void customSpeed(){final EditText e=new EditText(this);e.setInputType(2|8192);e.setHint("0.5 到 3.0");new AlertDialog.Builder(this).setTitle("自定义倍速").setView(e).setPositiveButton("确定",(d,w)->{try{float x=Float.parseFloat(e.getText().toString());service.setSpeed(Math.max(.5f,Math.min(3f,x)));}catch(Exception ignored){}}).setNegativeButton("取消",null).show();}
    private void skipDialog(){LinearLayout form=column(0);form.setPadding(dp(24),0,dp(24),0);form.addView(label("片头跳过秒数（每集开始时跳过）",14,INK,true));EditText intro=new EditText(this);intro.setInputType(android.text.InputType.TYPE_CLASS_NUMBER);intro.setText(String.valueOf(service.introSkip()/1000));form.addView(intro);form.addView(label("片尾跳过秒数（剩余这些秒时播放下一集）",14,INK,true));EditText outro=new EditText(this);outro.setInputType(android.text.InputType.TYPE_CLASS_NUMBER);outro.setText(String.valueOf(service.outroSkip()/1000));form.addView(outro);form.addView(label("填 0 可关闭，最大 600 秒。设置按总合集分别保存；过短的音频不会强制跳过。",12,MUTED,false));new AlertDialog.Builder(this).setTitle("跳过片头和片尾").setView(form).setPositiveButton("保存",(d,w)->{long a=parseSkipSeconds(intro),b=parseSkipSeconds(outro);service.setSkipTimes(a*1000,b*1000);refreshPlayerFields();Toast.makeText(this,"已保存：片头 "+a+" 秒，片尾 "+b+" 秒",Toast.LENGTH_SHORT).show();}).setNegativeButton("取消",null).show();}
    private long parseSkipSeconds(EditText input){try{return Math.max(0,Math.min(600,Long.parseLong(input.getText().toString().trim())));}catch(Exception ignored){return 0;}}
    private void sleepDialog(){String[] x={"10 分钟","20 分钟","30 分钟","60 分钟","当前音频结束","关闭定时"};new AlertDialog.Builder(this).setTitle("睡眠定时").setItems(x,(d,w)->{if(w<4){long[]m={10,20,30,60};service.sleepIn(m[w]*60000);}else if(w==4)service.sleepAfterTrack();else service.sleepIn(0);refreshPlayerFields();}).show();}
    private void bookmarkDialog(){LibraryDb.Track t=service.current();if(t==null)return;EditText note=new EditText(this);note.setHint("备注（可选）");new AlertDialog.Builder(this).setTitle("在 "+format(service.position())+" 添加书签").setView(note).setPositiveButton("保存",(d,w)->{db.addBookmark(t.uri,service.position(),note.getText().toString());Toast.makeText(this,"书签已保存",Toast.LENGTH_SHORT).show();}).setNeutralButton("查看书签",(d,w)->showBookmarks(t)).setNegativeButton("取消",null).show();}
    private void showBookmarks(LibraryDb.Track t){List<String[]> b=db.bookmarks(t.uri);if(b.isEmpty()){Toast.makeText(this,"这段音频还没有书签",Toast.LENGTH_SHORT).show();return;}String[] items=new String[b.size()];for(int i=0;i<b.size();i++)items[i]=format(Long.parseLong(b.get(i)[1]))+(b.get(i)[2].isEmpty()?"":"  ·  "+b.get(i)[2]);new AlertDialog.Builder(this).setTitle("书签").setItems(items,(d,w)->service.seekTo(Long.parseLong(b.get(w)[1]))).show();}

    private void refreshMini(){if(!bound||service.current()==null){if(mini!=null)mini.setVisibility(View.GONE);return;}mini.setVisibility(View.VISIBLE);LibraryDb.Track t=service.current();miniTitle.setText(t.displayTitle());miniState.setText((service.isPlaying()?"播放中 · ":"已暂停 · ")+format(service.position())+" / "+format(service.duration()));long d=service.duration();miniProgress.setProgress(d>0?(int)(service.position()*1000/d):0);View b=mini.findViewWithTag("miniPlay");if(b instanceof TextView)((TextView)b).setText(service.isPlaying()?"暂停":"播放");}
    private void pickFolder(){openFolderPicker(DocumentsContract.buildRootUri("com.android.externalstorage.documents","primary"));}
    private void openFolderPicker(Uri initialUri){if(scanning){Toast.makeText(this,"当前扫描尚未完成，请稍候再添加",Toast.LENGTH_SHORT).show();return;}if(pickingFolder)return;pickingFolder=true;Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT_TREE);i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION|Intent.FLAG_GRANT_PREFIX_URI_PERMISSION);i.putExtra(DocumentsContract.EXTRA_INITIAL_URI,initialUri);try{startActivityForResult(i,PICK_TREE);}catch(Exception e){pickingFolder=false;Toast.makeText(this,"无法打开系统文件夹选择器",Toast.LENGTH_LONG).show();}}
    private String coveringRoot(String authority,String selectedId){try{for(String[]root:db.roots()){if(root[0].startsWith("internal://"))continue;Uri rootUri=Uri.parse(root[0]);if(!Objects.equals(authority,rootUri.getAuthority()))continue;String rootId=DocumentsContract.getTreeDocumentId(rootUri);if(FolderIdentity.isSameOrDescendant(rootId,selectedId))return root[0];}}catch(Exception ignored){}return null;}
    @Override protected void onActivityResult(int req,int result,Intent data){super.onActivityResult(req,result,data);if(req!=PICK_TREE)return;pickingFolder=false;if(result!=RESULT_OK||data==null||scanning)return;Uri uri=data.getData();if(uri==null)return;String startId,name;try{startId=DocumentsContract.getTreeDocumentId(uri);name=folderDisplayName(uri);}catch(Exception e){Toast.makeText(this,"无法识别所选文件夹",Toast.LENGTH_LONG).show();return;}new FolderBrowserDialog(this,uri,startId,name,new FolderBrowserDialog.Listener(){public void onSelected(String documentId,String selectedName,String path){addSelectedFolder(uri,data,documentId,selectedName,path);}public void onCancelled(){showHome();}}).show();}
    private void addSelectedFolder(Uri pickerUri,Intent grantData,String documentId,String name,String path){if(scanning)return;String permissionUri=coveringRoot(pickerUri.getAuthority(),documentId);if(permissionUri==null){permissionUri=pickerUri.toString();try{if((grantData.getFlags()&Intent.FLAG_GRANT_READ_URI_PERMISSION)==0)throw new SecurityException("没有读取授权");getContentResolver().takePersistableUriPermission(pickerUri,Intent.FLAG_GRANT_READ_URI_PERMISSION);}catch(Exception e){Toast.makeText(this,"无法保存文件夹长期读取权限",Toast.LENGTH_LONG).show();return;}db.upsertRoot(permissionUri,folderDisplayName(pickerUri));}db.restoreExcludedDocument(documentId);if(db.coveringScanRoot(permissionUri,documentId)==null)db.upsertScanRoot(permissionUri,documentId,name,path);LibraryDb.Folder folder=new LibraryDb.Folder();folder.id=permissionUri+"#"+documentId;folder.rootUri=permissionUri;folder.parentId=null;folder.name=name;folder.path=path;beginScan();scanner.scanFolder(folder,scanCallback());}
    private String folderDisplayName(Uri uri){String id=DocumentsContract.getTreeDocumentId(uri);int p=id.lastIndexOf(':');String n=p>=0?id.substring(p+1):id;if(n.isEmpty())n="存储空间";int slash=n.lastIndexOf('/');return slash>=0?n.substring(slash+1):n;}
    private FolderScanner.Callback scanCallback(){return new FolderScanner.Callback(){public void onProgress(String t){}public void onDone(int f,int t){scanning=false;if(isFinishing()||isDestroyed())return;Toast.makeText(MainActivity.this,"扫描完成："+t+" 个音频，"+f+" 个文件夹",Toast.LENGTH_LONG).show();showHome();}public void onError(String m){scanning=false;if(isFinishing()||isDestroyed())return;Toast.makeText(MainActivity.this,"扫描失败："+m,Toast.LENGTH_LONG).show();showHome();}};}
    private void beginScan(){scanning=true;if(!isFinishing())showHome();Toast.makeText(this,"开始扫描，请稍候",Toast.LENGTH_SHORT).show();}
    private void rescan(){if(scanning){Toast.makeText(this,"当前扫描尚未完成",Toast.LENGTH_SHORT).show();return;}if(db.scanRoots().isEmpty()){pickFolder();return;}beginScan();scanner.scanAll(scanCallback());}

    private LinearLayout column(int gap){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);return l;}
    private LinearLayout card(){LinearLayout c=column(0);c.setPadding(dp(16),dp(15),dp(16),dp(15));c.setBackground(roundStroke(Color.WHITE,16,OUTLINE,1));LinearLayout.LayoutParams p=lp(-1,-2);p.setMargins(0,dp(7),0,dp(7));c.setLayoutParams(p);return c;}
    private TextView label(String s,int size,int color,boolean bold){TextView v=new TextView(this);v.setText(s);v.setTextSize(size);v.setTextColor(color);v.setTypeface(Typeface.create("sans",bold?Typeface.BOLD:Typeface.NORMAL));v.setLineSpacing(0,1.12f);return v;}
    private TextView sectionTitle(String s){TextView v=label(s,20,INK,true);v.setPadding(0,dp(20),0,dp(9));return v;}
    private Button button(String s){Button b=new Button(this);b.setText(s);b.setTextSize(13);b.setTextColor(INK);b.setAllCaps(false);b.setGravity(Gravity.CENTER);b.setBackgroundColor(Color.TRANSPARENT);b.setMinHeight(0);b.setMinimumHeight(0);b.setPadding(dp(10),0,dp(10),0);return b;}
    private void stylePrimary(Button b){b.setTextColor(Color.WHITE);b.setBackground(round(GREEN_DARK,22));b.setPadding(dp(16),0,dp(16),0);}
    private LinearLayout infoCard(String title,String body){LinearLayout c=card();c.addView(label(title,17,INK,true));TextView text=label(body,13,MUTED,false);text.setPadding(0,dp(5),0,0);c.addView(text);return c;}
    private Button sectionAction(String text){Button b=button(text);b.setTextColor(GREEN_DARK);b.setTextSize(12);b.setPadding(dp(10),0,dp(10),0);return b;}
    private SearchView searchBox(String hint){SearchView search=new SearchView(this);search.setQueryHint(hint);search.setIconifiedByDefault(false);search.setBackground(roundStroke(BLUE_SOFT,18,OUTLINE,1));try{int textId=getResources().getIdentifier("search_src_text","id","android");EditText input=search.findViewById(textId);if(input!=null){input.setTextColor(INK);input.setHintTextColor(MUTED);input.setTextSize(15);}int iconId=getResources().getIdentifier("search_mag_icon","id","android");ImageView icon=search.findViewById(iconId);if(icon!=null)icon.setColorFilter(MUTED);}catch(Exception ignored){}return search;}
    private ProgressBar styledProgress(int fill,int track){ProgressBar p=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);p.setProgressTintList(android.content.res.ColorStateList.valueOf(fill));p.setProgressBackgroundTintList(android.content.res.ColorStateList.valueOf(track));return p;}
    private View compactFolderCard(LibraryDb.Folder f){LinearLayout c=new LinearLayout(this);c.setTag("folder:"+f.id);c.setGravity(Gravity.CENTER_VERTICAL);c.setPadding(dp(10),dp(10),dp(8),dp(10));c.setBackground(roundStroke(Color.WHITE,12,OUTLINE,1));TextView icon=label("▰",18,GREEN_DARK,true);icon.setGravity(Gravity.CENTER);icon.setBackground(round(GREEN_SOFT,10));c.addView(icon,new LinearLayout.LayoutParams(dp(46),dp(46)));LinearLayout text=column(0);text.setPadding(dp(10),0,0,0);TextView name=label(f.name,15,INK,true);name.setSingleLine(true);name.setEllipsize(TextUtils.TruncateAt.END);text.addView(name);text.addView(label(f.count+" 个音频",12,MUTED,false));c.addView(text,new LinearLayout.LayoutParams(0,-2,1));c.setOnClickListener(v->showFolder(f.id));c.setOnLongClickListener(v->{folderMenu(f);return true;});LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(78),1);p.setMargins(dp(3),dp(3),dp(3),dp(3));c.setLayoutParams(p);return c;}
    private String episodeNumber(String name){String value=episodeLabel(name);return value.startsWith("第 ")?value.substring(2,value.length()-2).trim():"试听";}
    private GradientDrawable round(int color,int radius){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(dp(radius));return g;}
    private GradientDrawable roundStroke(int color,int radius,int stroke,int width){GradientDrawable g=round(color,radius);g.setStroke(dp(width),stroke);return g;}
    private LinearLayout.LayoutParams lp(int w,int h){return new LinearLayout.LayoutParams(w,h);}private int dp(int x){return (int)(x*getResources().getDisplayMetrics().density+.5f);}private String trimSpeed(float x){return x==(int)x?String.format(Locale.US,"%.1f",x):String.valueOf(x);}private static String format(long ms){long sec=Math.max(0,ms/1000),h=sec/3600,m=(sec%3600)/60,s=sec%60;return h>0?String.format(Locale.CHINA,"%d:%02d:%02d",h,m,s):String.format(Locale.CHINA,"%d:%02d",m,s);}
}
