package com.matianju.fm;

import android.app.*;
import android.content.*;
import android.media.*;
import android.media.session.*;
import android.net.Uri;
import android.os.*;
import java.util.*;

public final class PlayerService extends Service implements AudioManager.OnAudioFocusChangeListener {
    public static final String ACTION_PLAY="com.matianju.fm.PLAY",ACTION_PAUSE="com.matianju.fm.PAUSE",ACTION_NEXT="com.matianju.fm.NEXT",ACTION_PREV="com.matianju.fm.PREV",ACTION_STOP="com.matianju.fm.STOP";
    private static final String CHANNEL="playback"; private static final int NOTIFICATION=7;
    private final LocalBinder binder=new LocalBinder(); private final Handler handler=new Handler(Looper.getMainLooper());
    private MediaPlayer player; private MediaSession session; private AudioManager audio; private LibraryDb db; private List<LibraryDb.Track> queue=new ArrayList<>(); private int index=-1,mode=0; private float speed=1f; private long sleepAt=0,introSkipMs=0,outroSkipMs=0,lastPeriodicSave=0; private boolean stopAfterTrack=false,prepared=false,completing=false; private final InterruptionResumeState interruptionResume=new InterruptionResumeState();
    private final Runnable ticker=new Runnable(){public void run(){if(player!=null&&prepared){long now=System.currentTimeMillis();if(now-lastPeriodicSave>=5000){save(false);updateSession();lastPeriodicSave=now;}if(sleepAt>0&&now>=sleepAt){pause();sleepAt=0;}else if(isPlaying()&&shouldSkipOutro())completeCurrentTrack(true);}handler.postDelayed(this,500);}};
    private final BroadcastReceiver noisy=new BroadcastReceiver(){public void onReceive(Context c,Intent i){if(AudioManager.ACTION_AUDIO_BECOMING_NOISY.equals(i.getAction()))pause();}};

    public final class LocalBinder extends Binder { public PlayerService service(){return PlayerService.this;} }
    @Override public void onCreate(){super.onCreate();db=LibraryDb.get(this);audio=(AudioManager)getSystemService(AUDIO_SERVICE);createChannel();createSession();IntentFilter f=new IntentFilter(AudioManager.ACTION_AUDIO_BECOMING_NOISY);if(Build.VERSION.SDK_INT>=33)registerReceiver(noisy,f,RECEIVER_NOT_EXPORTED);else registerReceiver(noisy,f);handler.post(ticker);}
    @Override public android.os.IBinder onBind(Intent i){return binder;}
    @Override public int onStartCommand(Intent i,int flags,int id){if(i!=null&&i.getAction()!=null)switch(i.getAction()){case ACTION_PLAY:toggle();break;case ACTION_PAUSE:pause();break;case ACTION_NEXT:next();break;case ACTION_PREV:previous();break;case ACTION_STOP:pause();stopForeground(STOP_FOREGROUND_REMOVE);break;}return START_NOT_STICKY;}
    @Override public void onDestroy(){save(false);handler.removeCallbacks(ticker);try{unregisterReceiver(noisy);}catch(Exception ignored){}if(player!=null)player.release();session.release();audio.abandonAudioFocus(this);super.onDestroy();}
    @Override public void onTaskRemoved(Intent rootIntent){save(false);super.onTaskRemoved(rootIntent);}

    private void createSession(){session=new MediaSession(this,"MaTianJuFM");session.setCallback(new MediaSession.Callback(){@Override public void onPlay(){play();}@Override public void onPause(){pause();}@Override public void onSkipToNext(){next();}@Override public void onSkipToPrevious(){previous();}@Override public void onSeekTo(long p){seekTo(p);}@Override public void onStop(){pause();}});session.setFlags(MediaSession.FLAG_HANDLES_MEDIA_BUTTONS|MediaSession.FLAG_HANDLES_TRANSPORT_CONTROLS);session.setActive(true);}
    private void createChannel(){NotificationChannel c=new NotificationChannel(CHANNEL,"音频播放",NotificationManager.IMPORTANCE_LOW);c.setDescription("后台播放与锁屏控制");((NotificationManager)getSystemService(NOTIFICATION_SERVICE)).createNotificationChannel(c);}
    private PendingIntent serviceAction(String action,int code){Intent i=new Intent(this,PlayerService.class).setAction(action);return PendingIntent.getService(this,code,i,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);}
    private Notification notification(){LibraryDb.Track t=current();String title=t==null?"马天驹 FM":t.displayTitle();String sub=t==null?"本地音频播放器":folderName(t.folderId);Intent open=new Intent(this,MainActivity.class).addFlags(Intent.FLAG_ACTIVITY_SINGLE_TOP);PendingIntent content=PendingIntent.getActivity(this,0,open,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);
        Notification.Action prev=new Notification.Action.Builder(android.R.drawable.ic_media_previous,"上一首",serviceAction(ACTION_PREV,1)).build();
        boolean playing=isPlaying();Notification.Action center=new Notification.Action.Builder(playing?android.R.drawable.ic_media_pause:android.R.drawable.ic_media_play,playing?"暂停":"播放",serviceAction(playing?ACTION_PAUSE:ACTION_PLAY,2)).build();
        Notification.Action next=new Notification.Action.Builder(android.R.drawable.ic_media_next,"下一首",serviceAction(ACTION_NEXT,3)).build();
        return new Notification.Builder(this,CHANNEL).setSmallIcon(R.drawable.ic_app).setContentTitle(title).setContentText(sub).setContentIntent(content).setOnlyAlertOnce(true).setOngoing(playing).setVisibility(Notification.VISIBILITY_PUBLIC).addAction(prev).addAction(center).addAction(next).setStyle(new Notification.MediaStyle().setMediaSession(session.getSessionToken()).setShowActionsInCompactView(0,1,2)).build();}
    private String folderName(String id){LibraryDb.Folder f=db.folder(id);return f==null?"本地音频":f.name;}
    private void showNotification(){Notification n=notification();if(isPlaying())startForeground(NOTIFICATION,n);else((NotificationManager)getSystemService(NOTIFICATION_SERVICE)).notify(NOTIFICATION,n);}

    public void loadQueue(List<LibraryDb.Track> tracks,int at,boolean autoplay){save(false);mode=0;queue=new ArrayList<>(tracks);index=Math.max(0,Math.min(at,queue.size()-1));loadCurrent(autoplay,true);}
    private void loadCurrent(boolean autoplay,boolean resume){LibraryDb.Track t=current();if(t==null)return;prepared=false;completing=false;loadSkipSettings(t);if(player!=null){player.reset();}else{player=new MediaPlayer();player.setWakeMode(this,PowerManager.PARTIAL_WAKE_LOCK);player.setAudioAttributes(new AudioAttributes.Builder().setUsage(AudioAttributes.USAGE_MEDIA).setContentType(AudioAttributes.CONTENT_TYPE_SPEECH).build());}
        try{player.setDataSource(this,Uri.parse(t.uri));player.setOnPreparedListener(mp->{prepared=true;lastPeriodicSave=System.currentTimeMillis();try{mp.setPlaybackParams(mp.getPlaybackParams().setSpeed(speed));}catch(Exception ignored){}long saved=resume&&!t.completed?Math.max(0,t.position-5000):0,start=Math.max(saved,effectiveIntro(mp.getDuration()));if(start>0&&start<mp.getDuration())mp.seekTo((int)start);if(autoplay)play();else{updateSession();showNotification();}});player.setOnCompletionListener(mp->completeCurrentTrack(false));player.setOnErrorListener((mp,w,e)->{prepared=false;nextInternal(true);return true;});player.prepareAsync();updateSession();showNotification();}catch(Exception e){prepared=false;nextInternal(autoplay);}}
    private boolean requestFocus(){int r=audio.requestAudioFocus(this,AudioManager.STREAM_MUSIC,AudioManager.AUDIOFOCUS_GAIN);return r==AudioManager.AUDIOFOCUS_REQUEST_GRANTED;}
    public void play(){if(player==null){LibraryDb.Track t=db.lastPlayed();if(t!=null){String profile=db.playbackProfileId(t.folderId);List<LibraryDb.Track>q=db.tracksInSubtree(profile,null,false);int at=0;for(int i=0;i<q.size();i++)if(q.get(i).uri.equals(t.uri))at=i;loadQueue(q,at,true);}return;}if(prepared&&requestFocus()){player.start();showNotification();updateSession();}}
    public void pause(){interruptionResume.onManualPause();pauseInternal();}
    private void pauseInternal(){if(player!=null&&prepared&&player.isPlaying())player.pause();save(false);showNotification();updateSession();}
    public void stopAndClear(){save(false);prepared=false;if(player!=null){try{player.stop();}catch(Exception ignored){}player.release();player=null;}queue.clear();index=-1;stopForeground(STOP_FOREGROUND_REMOVE);((NotificationManager)getSystemService(NOTIFICATION_SERVICE)).cancel(NOTIFICATION);session.setPlaybackState(new PlaybackState.Builder().setState(PlaybackState.STATE_STOPPED,0,0).build());}
    public void toggle(){if(isPlaying())pause();else play();}
    public void next(){nextInternal(true);}private void nextInternal(boolean autoplay){if(queue.isEmpty())return;save(false);if(mode==3)index=new Random().nextInt(queue.size());else if(index+1<queue.size())index++;else if(mode==2)index=0;else{pause();return;}loadCurrent(autoplay,true);}
    public void previous(){if(queue.isEmpty())return;save(false);index=QueueNavigation.previousIndex(index,queue.size(),mode==2);loadCurrent(true,false);}
    public void seekTo(long p){if(player!=null&&prepared){player.seekTo((int)Math.max(0,Math.min(p,player.getDuration())));save(false);updateSession();}}
    public void skip(long delta){seekTo(position()+delta);}
    private void save(boolean complete){LibraryDb.Track t=current();if(t!=null&&player!=null&&prepared)db.saveProgress(t.uri,player.getCurrentPosition(),player.getDuration(),complete);}
    private long effectiveIntro(long duration){return PlaybackSkip.effectiveIntro(duration,introSkipMs,outroSkipMs);}
    private boolean shouldSkipOutro(){return player!=null&&prepared&&PlaybackSkip.shouldSkipOutro(player.getDuration(),player.getCurrentPosition(),introSkipMs,outroSkipMs);}
    private void completeCurrentTrack(boolean skipOutro){if(completing||!prepared)return;completing=true;save(true);if(skipOutro&&player!=null)try{player.pause();}catch(Exception ignored){}prepared=false;if(stopAfterTrack){stopAfterTrack=false;completing=false;showNotification();updateSession();return;}completing=false;if(mode==1)loadCurrent(true,false);else nextInternal(true);}
    private void loadSkipSettings(LibraryDb.Track track){String profile=db.playbackProfileId(track.folderId);introSkipMs=parseMillis(db.setting("skip_intro_"+profile,"0"));outroSkipMs=parseMillis(db.setting("skip_outro_"+profile,"0"));try{speed=Math.max(.5f,Math.min(3f,Float.parseFloat(db.setting("speed_"+profile,"1.0"))));}catch(Exception ignored){speed=1f;}}
    private long parseMillis(String value){try{return PlaybackSkip.clamp(Long.parseLong(value));}catch(Exception ignored){return 0;}}
    private void updateSession(){LibraryDb.Track t=current();if(t==null)return;session.setMetadata(new MediaMetadata.Builder().putString(MediaMetadata.METADATA_KEY_TITLE,t.displayTitle()).putString(MediaMetadata.METADATA_KEY_ARTIST,folderName(t.folderId)).putLong(MediaMetadata.METADATA_KEY_DURATION,duration()).build());long actions=PlaybackState.ACTION_PLAY|PlaybackState.ACTION_PAUSE|PlaybackState.ACTION_PLAY_PAUSE|PlaybackState.ACTION_SEEK_TO|PlaybackState.ACTION_SKIP_TO_NEXT|PlaybackState.ACTION_SKIP_TO_PREVIOUS;session.setPlaybackState(new PlaybackState.Builder().setActions(actions).setState(isPlaying()?PlaybackState.STATE_PLAYING:PlaybackState.STATE_PAUSED,position(),isPlaying()?speed:0f).build());}
    @Override public void onAudioFocusChange(int change){if(change==AudioManager.AUDIOFOCUS_LOSS){interruptionResume.onPermanentLoss();pauseInternal();}else if(change==AudioManager.AUDIOFOCUS_LOSS_TRANSIENT){interruptionResume.onTransientLoss(isPlaying());pauseInternal();}else if(change==AudioManager.AUDIOFOCUS_LOSS_TRANSIENT_CAN_DUCK&&player!=null)player.setVolume(.25f,.25f);else if(change==AudioManager.AUDIOFOCUS_GAIN){if(player!=null)player.setVolume(1f,1f);if(interruptionResume.consumeOnGain()&&player!=null&&prepared&&!player.isPlaying()){try{player.start();showNotification();updateSession();}catch(Exception ignored){}}}}
    public LibraryDb.Track current(){return index>=0&&index<queue.size()?queue.get(index):null;} public boolean isPlaying(){return player!=null&&prepared&&player.isPlaying();}public long position(){return player!=null&&prepared?player.getCurrentPosition():0;}public long duration(){return player!=null&&prepared?player.getDuration():(current()==null?0:current().duration);}
    public void setSpeed(float value){speed=value;String profile=current()==null?"default":db.playbackProfileId(current().folderId);db.setSetting("speed_"+profile,String.valueOf(value));if(player!=null&&prepared)try{player.setPlaybackParams(player.getPlaybackParams().setSpeed(value));}catch(Exception ignored){}updateSession();}public float speed(){return speed;}
    public void setSkipTimes(long introMillis,long outroMillis){introSkipMs=PlaybackSkip.clamp(introMillis);outroSkipMs=PlaybackSkip.clamp(outroMillis);String profile=current()==null?"default":db.playbackProfileId(current().folderId);db.setSetting("skip_intro_"+profile,String.valueOf(introSkipMs));db.setSetting("skip_outro_"+profile,String.valueOf(outroSkipMs));}public long introSkip(){return introSkipMs;}public long outroSkip(){return outroSkipMs;}
    public void setMode(int value){mode=value;}public int mode(){return mode;}public void sleepIn(long millis){sleepAt=millis<=0?0:System.currentTimeMillis()+millis;stopAfterTrack=false;}public void sleepAfterTrack(){sleepAt=0;stopAfterTrack=true;}public long sleepRemaining(){return sleepAt==0?0:Math.max(0,sleepAt-System.currentTimeMillis());}public boolean sleepAfterTrackEnabled(){return stopAfterTrack;}
}
